# Import libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Get the data

In [3]:
# Load the dataset from the CSV file
dataset = pd.read_csv('../data/book700k-800k.csv')
df = pd.DataFrame({'Id': dataset['Id'],
                        'Name': dataset['Name'],
                        'Authors': dataset['Authors'],
                        'Rating': dataset['Rating'],
                        'Description': dataset['Description']})

# Display the first few rows of the dataset
df.head

<bound method NDFrame.head of            Id                                               Name  \
0      700000  A Passion to Preserve: Gay Men as Keepers of C...
1      700002  Culture Keepers-Florida: Oral History of the A...
2      700003  Holiday Favorites: The Best of the Williams-So...
3      700004  Soups, Salads & Starters: the Best of Williams...
4      700005                              Breakfasts & Brunches
...       ...                                                ...
54268  799991           Piano Concerto Highlights for Solo Piano
54269  799993  Noggin King of the Nogs (The Sagas of Noggin t...
54270  799994  No Greater Glory: The Four Immortal Chaplains ...
54271  799996  The White Company by Arthur Conan Doyle, Ficti...
54272  799997                    Livewire Real Lives Dawn Fraser

                     Authors  Rating  \
0               Will Fellows    3.75
1      Deborah Johnson-Simon    0.00
2            Allen Rosenberg    4.55
3            Allan Rosenberg    4.70
4            Time-Life Books    3.88
...                      ...     ...
54268         Felix Guenther    5.00
54269        Oliver Postgate    4.38
54270            Dan Kurzman    4.02
54271     Arthur Conan Doyle    3.89
54272            Ian Jackson    0.00

                                             Description
0      From large cities to rural communities, gay me...
1                                                    NaN
2      This collector's edition features fabulous ful...
3                                                    NaN
4      America's most respected cookware retailer, th...
...                                                  ...
54268  Concertos are every pianist's pinnacle of perf...
54269  1. King of the Nogs --<br />2. The ice dragon ...
54270  The sinking of the <i>Dorchester</i> in the ic...
54271  "By my hilt!" cried the other, "if you were to...
54272  This book tells the story of Dawn Fraser, vote...

[54273 rows x 5 columns]>

In [4]:
# Replace Nan values with ''
df['Description'] = df['Description'].fillna('')
ori_description = df['Description']

In [5]:
df['Description'][0]

'From large cities to rural communities, gay men have long been impassioned pioneers as keepers of culture: rescuing and restoring decrepit buildings, revitalizing blighted neighborhoods, saving artifacts and documents of historical significance. <i>A Passion to Preserve</i> explores this authentic and complex dimension of gay men’s lives by profiling early and contemporary preservationists from throughout the United States, highlighting contributions to the larger culture that gays are exceptionally inclined to make.'

# Data preprocessing

In [6]:
import re
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Initialize the stopwords
stop_words = set(stopwords.words('english'))

def preprocessing_text(text):
    # Convert the input text to string
    text = str(text)
    
    # Convert text to lowercase
    text = text.lower()
    
    # Remove special characters and digits and replace them with a spcae
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    
    # Tokenize the text
    tokens = nltk.word_tokenize(text)
    
    # Remove stop words
    tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatize the tokens (convert words into their base dictionary form, ex. cats->cat)
    tokens = [lemmatizer.lemmatize(word, pos='v') for word in tokens]
    
    # Return the processed text as a string
    return " ".join(tokens)


def preprocess_dataframe(df, column_name):
    df[column_name ]= df[column_name].apply(preprocessing_text)
    return df

df = preprocess_dataframe(df=df, column_name='Description')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [7]:
df['Description'].head

<bound method NDFrame.head of 0        large cities rural communities gay men long im...
1
2        collector edition feature fabulous full color ...
3
4        america respect cookware retailer world larges...
                               ...
54268    concertos every pianist pinnacle performance r...
54269    king nogs br ice dragon br fly machine br omru...
54270    sink dorchester icy water greenland shortly mi...
54271    hilt cry cross narrow sea would find thick be ...
54272    book tell story dawn fraser vote greatest fema...
Name: Description, Length: 54273, dtype: str>

# Get text features using tf-idf

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

def get_text_feature(df):
    description = df['Description']
    # Text feature
    tfidf = TfidfVectorizer(stop_words="english",
                            strip_accents='ascii',
                            token_pattern=r'\w+')

    tfidf_matrix = tfidf.fit_transform(description)
    tfidf.get_feature_names_out()
    
    return tfidf_matrix
tfidf_matrix = get_text_feature(df=df)

# Calculate cosine similarity
`from sklearn.metrics.pairwise import cosine_similarity`

In [9]:
from sklearn.metrics.pairwise import cosine_similarity

def calculate_cosine_similarity_of_a_target_book(book, tfidf_matrix):
    """Calculate the cosine similarity between a target book and all books
    in the TF-IDF matrix.

    Args:
        book (scipy.sparse.csr_matrix): 
            A single TF-IDF row vector representing the target book.
            Shape should be (1, n_features).
        tfidf_matrix (scipy.sparse.csr_matrix_): 
            TF-IDF matrix containing all book vectors.
            Shape should be (n_books, n_features).

    Returns:
        numpy.ndarray: A 2D array containing cosine similarity scores between the target book and 
        every book in the TF-IDF matrix.
        Shape will be (1, n_books).
    """
    X = book
    Y = tfidf_matrix
    cs = cosine_similarity(X, Y)
    return cs

book = calculate_cosine_similarity_of_a_target_book(tfidf_matrix=tfidf_matrix, book=tfidf_matrix[0])
book

array([[1.        , 0.        , 0.        , ..., 0.02897096, 0.        ,
        0.00840239]], shape=(1, 54273))

# Add indices to the similarity array

In [10]:
tfidf_matrix.shape[0]

54273

In [11]:
def add_indices(sim_array):
    indexed_array = []
    for i, s in zip(range(tfidf_matrix.shape[0]), sim_array[0]):
        indexed_array.append((i, s))
    return indexed_array
    
book_idx = add_indices(book)
book_idx

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(0.0)),
 (5, np.float64(0.004262619544149328)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.02615232813989701)),
 (9, np.float64(0.005407582828292852)),
 (10, np.float64(0.006454727247923977)),
 (11, np.float64(0.001721123833796132)),
 (12, np.float64(0.033500104283204046)),
 (13, np.float64(0.0)),
 (14, np.float64(0.03093034732586701)),
 (15, np.float64(0.0)),
 (16, np.float64(0.012516813137672417)),
 (17, np.float64(0.0)),
 (18, np.float64(0.004277249851112908)),
 (19, np.float64(0.02021633193542061)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.03540015278127994)),
 (23, np.float64(0.004704280694827859)),
 (24, np.float64(0.039896463913302024)),
 (25, np.float64(0.018351783433114693)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.0)),
 (31, np.float64(0.006827960479232422)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.004088499142603447)),
 (35, np.float64(0.0)),
 (36, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.004103860541871123)),
 (40, np.float64(0.0)),
 (41, np.float64(0.036930029410413276)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.03001845010896187)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.004642564430491798)),
 (50, np.float64(0.0)),
 (51, np.float64(0.01873878505614305)),
 (52, np.float64(0.013676472873796839)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.02315808280281991)),
 (56, np.float64(0.0)),
 (57, np.float64(0.010833312570743096)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.020032750798836967)),
 (61, np.float64(0.007429709653217918)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.009176222577041317)),
 (65, np.float64(0.014556539240483342)),
 (66, np.float64(0.021910883983828542)),
 (67, np.float64(0.0)),
 (68, np.float64(0.008718731836441718)),
 (69, np.float64(0.0)),
 (70, np.float64(0.009338633010167106)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.008182899504179303)),
 (75, np.float64(0.010768127021660856)),
 (76, np.float64(0.0)),
 (77, np.float64(0.033908459591796766)),
 (78, np.float64(0.013567629698945604)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.011211967289063898)),
 (83, np.float64(0.0)),
 (84, np.float64(0.01629553173707787)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.0320898840192375)),
 (88, np.float64(0.04050079673769965)),
 (89, np.float64(0.023460021872482063)),
 (90, np.float64(0.0)),
 (91, np.float64(0.02180723156474596)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0030782821766990325)),
 (94, np.float64(0.031577883403713716)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.002124513752074634)),
 (98, np.float64(0.004124088311897883)),
 (99, np.float64(0.009869131212049916)),
 (100, np.float64(0.0)),
 (101, np.float64(0.024901231167261013)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.013763528200689785)),
 (107, np.float64(0.0)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.01963575859372987)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.008023998974210972)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.009591791004678447)),
 (124, np.float64(0.0)),
 (125, np.float64(0.02227411083901458)),
 (126, np.float64(0.01507164480442525)),
 (127, np.float64(0.028953224382852638)),
 (128, np.float64(0.023078261586685845)),
 (129, np.float64(0.021123631164052324)),
 (130, np.float64(0.010830132720093089)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.00460964264959414)),
 (135, np.float64(0.0)),
 (136, np.float64(0.006588146246297217)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.034807985099722265)),
 (140, np.float64(0.0)),
 (141, np.float64(0.014646418376052964)),
 (142, np.float64(0.028492423146081185)),
 (143, np.float64(0.018074484890221513)),
 (144, np.float64(0.0)),
 (145, np.float64(0.010678263078813402)),
 (146, np.float64(0.033580485187203794)),
 (147, np.float64(0.00835478514837873)),
 (148, np.float64(0.005880350322225799)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.004697575389571579)),
 (152, np.float64(0.0)),
 (153, np.float64(0.0084414955782252)),
 (154, np.float64(0.00287538317679985)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.019855773026453652)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.013869560926683825)),
 (162, np.float64(0.0)),
 (163, np.float64(0.013902437605609452)),
 (164, np.float64(0.0)),
 (165, np.float64(0.014166541714544423)),
 (166, np.float64(0.0024723912789276032)),
 (167, np.float64(0.026187688042450138)),
 (168, np.float64(0.017745312096397473)),
 (169, np.float64(0.0016424826650705028)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0034461103691210354)),
 (173, np.float64(0.004392811468567792)),
 (174, np.float64(0.0063320998955734824)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.019584685794313387)),
 (179, np.float64(0.0)),
 (180, np.float64(0.02324591712581041)),
 (181, np.float64(0.0196356198119815)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.014435522705908853)),
 (186, np.float64(0.02444541552099091)),
 (187, np.float64(0.0)),
 (188, np.float64(0.02407752016637021)),
 (189, np.float64(0.020258179970566295)),
 (190, np.float64(0.032173472087778515)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.007214363022549967)),
 (194, np.float64(0.0)),
 (195, np.float64(0.004348996648649613)),
 (196, np.float64(0.010673940590591763)),
 (197, np.float64(0.0026432606624663575)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.027382653718254137)),
 (201, np.float64(0.023343019298938877)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.004848342766311163)),
 (205, np.float64(0.0)),
 (206, np.float64(0.003150693035795457)),
 (207, np.float64(0.008107438137600733)),
 (208, np.float64(0.014759020924372854)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0074774807817465155)),
 (211, np.float64(0.0017225913579550843)),
 (212, np.float64(0.0)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.016379610040267403)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0046173669638721075)),
 (219, np.float64(0.021157111911617017)),
 (220, np.float64(0.0)),
 (221, np.float64(0.018599401398695856)),
 (222, np.float64(0.007740824009677251)),
 (223, np.float64(0.0)),
 (224, np.float64(0.010588895898120546)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.011960564827476096)),
 (230, np.float64(0.02742831566844416)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.01622866053790436)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.03001845010896187)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0147304302876445)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.008159731079994646)),
 (244, np.float64(0.02268968190377181)),
 (245, np.float64(0.0)),
 (246, np.float64(0.00824129299642068)),
 (247, np.float64(0.0032235880447053643)),
 (248, np.float64(0.0)),
 (249, np.float64(0.015227202808502524)),
 (250, np.float64(0.0208278210835043)),
 (251, np.float64(0.014951712823299552)),
 (252, np.float64(0.0064093393949963395)),
 (253, np.float64(0.03001845010896187)),
 (254, np.float64(0.00557618096472887)),
 (255, np.float64(0.004965195878436835)),
 (256, np.float64(0.0020837810007003324)),
 (257, np.float64(0.0031560644742544457)),
 (258, np.float64(0.014925950751302373)),
 (259, np.float64(0.0)),
 (260, np.float64(0.014544315947659535)),
 (261, np.float64(0.0)),
 (262, np.float64(0.003187653878090688)),
 (263, np.float64(0.013542384926099193)),
 (264, np.float64(0.0)),
 (265, np.float64(0.009370317425616372)),
 (266, np.float64(0.0072248122546033355)),
 (267, np.float64(0.0)),
 (268, np.float64(0.019734694797795414)),
 (269, np.float64(0.0)),
 (270, np.float64(0.007810845784529397)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.017268376071205297)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.0022865087433872953)),
 (278, np.float64(0.007197943974031786)),
 (279, np.float64(0.02300388151302013)),
 (280, np.float64(0.002437503563887876)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.009392127305786506)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0030657462660518167)),
 (289, np.float64(0.007640400347333652)),
 (290, np.float64(0.005077389995298244)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.005782708714045112)),
 (296, np.float64(0.0)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.029924712706511692)),
 (300, np.float64(0.0)),
 (301, np.float64(0.022734754604940375)),
 (302, np.float64(0.012845234642088761)),
 (303, np.float64(0.0)),
 (304, np.float64(0.0114311213915134)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.0026197129585006744)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.01091093342192431)),
 (311, np.float64(0.011026834832756632)),
 (312, np.float64(0.0)),
 (313, np.float64(0.0)),
 (314, np.float64(0.009605292957563598)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.009779211589847547)),
 (318, np.float64(0.017977940661975965)),
 (319, np.float64(0.012677969202229975)),
 (320, np.float64(0.01494357655727523)),
 (321, np.float64(0.015485773409790663)),
 (322, np.float64(0.009705972668566158)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.02271872707351976)),
 (328, np.float64(0.06948520864378308)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.026914759282699246)),
 (332, np.float64(0.008422283059865346)),
 (333, np.float64(0.011778816142462508)),
 (334, np.float64(0.0)),
 (335, np.float64(0.005175791448587197)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.01333094467928718)),
 (340, np.float64(0.0)),
 (341, np.float64(0.013893705498837514)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.023227642315783968)),
 (345, np.float64(0.016563946928841236)),
 (346, np.float64(0.02499527963974398)),
 (347, np.float64(0.01938209242501062)),
 (348, np.float64(0.0)),
 (349, np.float64(0.015298692937768338)),
 (350, np.float64(0.004294258832110969)),
 (351, np.float64(0.009075365476943875)),
 (352, np.float64(0.0)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.0)),
 (357, np.float64(0.0124493799016967)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0021972127434444198)),
 (363, np.float64(0.0)),
 (364, np.float64(0.006463717553846421)),
 (365, np.float64(0.0068947547893193125)),
 (366, np.float64(0.005448923310699018)),
 (367, np.float64(0.027194445433751494)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.03440402835211617)),
 (372, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.03994945410523473)),
 (377, np.float64(0.019575883674058145)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.021879319802730196)),
 (381, np.float64(0.022948401206252952)),
 (382, np.float64(0.023657284576194287)),
 (383, np.float64(0.04520495080560537)),
 (384, np.float64(0.044391511368077195)),
 (385, np.float64(0.020509598544517144)),
 (386, np.float64(0.08024171549608934)),
 (387, np.float64(0.0819066191249451)),
 (388, np.float64(0.014074221420297729)),
 (389, np.float64(0.01156829607322948)),
 (390, np.float64(0.004098062386879047)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.02259264396501823)),
 (395, np.float64(0.016637349792977065)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.022569904811670684)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0030972707638411163)),
 (401, np.float64(0.005780878695521852)),
 (402, np.float64(0.005132331134583698)),
 (403, np.float64(0.006476600013746463)),
 (404, np.float64(0.0)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.03001845010896187)),
 (409, np.float64(0.0172850328067368)),
 (410, np.float64(0.011799697795756863)),
 (411, np.float64(0.014120690794919922)),
 (412, np.float64(0.012286626875190628)),
 (413, np.float64(0.032113501988870044)),
 (414, np.float64(0.02444071586454471)),
 (415, np.float64(0.04595169661788638)),
 (416, np.float64(0.03700500363949519)),
 (417, np.float64(0.0)),
 (418, np.float64(0.02065463334507915)),
 (419, np.float64(0.009137459445981443)),
 (420, np.float64(0.012730478213370828)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0032979799955424475)),
 (424, np.float64(0.0)),
 (425, np.float64(0.00512261445229682)),
 (426, np.float64(0.0)),
 (427, np.float64(0.010406842140857415)),
 (428, np.float64(0.026842879250297474)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.015102289765436523)),
 (434, np.float64(0.015213332103016498)),
 (435, np.float64(0.004342307145560978)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.016388164350644153)),
 (440, np.float64(0.0)),
 (441, np.float64(0.022947806652170725)),
 (442, np.float64(0.004800379039447179)),
 (443, np.float64(0.024910941639351612)),
 (444, np.float64(0.0)),
 (445, np.float64(0.04183181711602073)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.00297585691241289)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.013279752391352007)),
 (455, np.float64(0.007076572567583822)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.006418867332576837)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.01970015143428707)),
 (470, np.float64(0.021337067675705673)),
 (471, np.float64(0.013775012153961642)),
 (472, np.float64(0.019669730371413896)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.03341225082623925)),
 (476, np.float64(0.02475180988173646)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.01810413421613658)),
 (480, np.float64(0.009662890015353151)),
 (481, np.float64(0.043943585765211124)),
 (482, np.float64(0.001445676672534338)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.020205135189134426)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.02264772722321082)),
 (489, np.float64(0.021628811404938407)),
 (490, np.float64(0.0)),
 (491, np.float64(0.0)),
 (492, np.float64(0.005334330832631217)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.010587020167205525)),
 (496, np.float64(0.020268707327932324)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0)),
 (499, np.float64(0.011372233571206366)),
 (500, np.float64(0.0)),
 (501, np.float64(0.005130194370818888)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0013627881473615574)),
 (505, np.float64(0.0)),
 (506, np.float64(0.02335456994381423)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.010153393962379964)),
 (510, np.float64(0.01877858481035832)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.010034781209449886)),
 (515, np.float64(0.0)),
 (516, np.float64(0.009140186901715206)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.009207513780446918)),
 (520, np.float64(0.0)),
 (521, np.float64(0.013875269407272035)),
 (522, np.float64(0.0)),
 (523, np.float64(0.017491979234640326)),
 (524, np.float64(0.026029500250742063)),
 (525, np.float64(0.03029004563526326)),
 (526, np.float64(0.008423776184001952)),
 (527, np.float64(0.01813326617328362)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.022599999706723117)),
 (533, np.float64(0.016625592366082086)),
 (534, np.float64(0.03350031116223012)),
 (535, np.float64(0.046016983033189504)),
 (536, np.float64(0.027364677324737106)),
 (537, np.float64(0.02374947458102507)),
 (538, np.float64(0.010690373958996692)),
 (539, np.float64(0.03747920629696514)),
 (540, np.float64(0.022479043198673533)),
 (541, np.float64(0.0)),
 (542, np.float64(0.009132137766841828)),
 (543, np.float64(0.0235100379402279)),
 (544, np.float64(0.0)),
 (545, np.float64(0.027969999472758716)),
 (546, np.float64(0.0)),
 (547, np.float64(0.03497402879708919)),
 (548, np.float64(0.009840649797829074)),
 (549, np.float64(0.015264173364887827)),
 (550, np.float64(0.018104719837678605)),
 (551, np.float64(0.013744456253425404)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.00694369881807455)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.035966086901001046)),
 (558, np.float64(0.013289960870115658)),
 (559, np.float64(0.0)),
 (560, np.float64(0.009152786245938965)),
 (561, np.float64(0.0)),
 (562, np.float64(0.042686197170836916)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.008879635709481342)),
 (566, np.float64(0.004785499419698542)),
 (567, np.float64(0.0)),
 (568, np.float64(0.024903274905888593)),
 (569, np.float64(0.017552108899483748)),
 (570, np.float64(0.0)),
 (571, np.float64(0.006963661731280012)),
 (572, np.float64(0.0157590761800748)),
 (573, np.float64(0.0036175474357959445)),
 (574, np.float64(0.0)),
 (575, np.float64(0.003914020861400064)),
 (576, np.float64(0.04509875169324787)),
 (577, np.float64(0.011402413552619473)),
 (578, np.float64(0.025044722875722934)),
 (579, np.float64(0.016389676484386814)),
 (580, np.float64(0.0)),
 (581, np.float64(0.006943886646890642)),
 (582, np.float64(0.0)),
 (583, np.float64(0.008124354535867677)),
 (584, np.float64(0.009511243190721467)),
 (585, np.float64(0.04340206604607845)),
 (586, np.float64(0.007371934495256454)),
 (587, np.float64(0.014939275053680905)),
 (588, np.float64(0.0)),
 (589, np.float64(0.02411322782898219)),
 (590, np.float64(0.004869095920834748)),
 (591, np.float64(0.007941275793145162)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.02550353701784512)),
 (595, np.float64(0.0)),
 (596, np.float64(0.006180133389718298)),
 (597, np.float64(0.01497631110996746)),
 (598, np.float64(0.0)),

# Sort descendent

In [12]:
book_idx

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(0.0)),
 (5, np.float64(0.004262619544149328)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.02615232813989701)),
 (9, np.float64(0.005407582828292852)),
 (10, np.float64(0.006454727247923977)),
 (11, np.float64(0.001721123833796132)),
 (12, np.float64(0.033500104283204046)),
 (13, np.float64(0.0)),
 (14, np.float64(0.03093034732586701)),
 (15, np.float64(0.0)),
 (16, np.float64(0.012516813137672417)),
 (17, np.float64(0.0)),
 (18, np.float64(0.004277249851112908)),
 (19, np.float64(0.02021633193542061)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.03540015278127994)),
 (23, np.float64(0.004704280694827859)),
 (24, np.float64(0.039896463913302024)),
 (25, np.float64(0.018351783433114693)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.0)),
 (31, np.float64(0.006827960479232422)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.004088499142603447)),
 (35, np.float64(0.0)),
 (36, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.004103860541871123)),
 (40, np.float64(0.0)),
 (41, np.float64(0.036930029410413276)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.03001845010896187)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.004642564430491798)),
 (50, np.float64(0.0)),
 (51, np.float64(0.01873878505614305)),
 (52, np.float64(0.013676472873796839)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.02315808280281991)),
 (56, np.float64(0.0)),
 (57, np.float64(0.010833312570743096)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.020032750798836967)),
 (61, np.float64(0.007429709653217918)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.009176222577041317)),
 (65, np.float64(0.014556539240483342)),
 (66, np.float64(0.021910883983828542)),
 (67, np.float64(0.0)),
 (68, np.float64(0.008718731836441718)),
 (69, np.float64(0.0)),
 (70, np.float64(0.009338633010167106)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.008182899504179303)),
 (75, np.float64(0.010768127021660856)),
 (76, np.float64(0.0)),
 (77, np.float64(0.033908459591796766)),
 (78, np.float64(0.013567629698945604)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.011211967289063898)),
 (83, np.float64(0.0)),
 (84, np.float64(0.01629553173707787)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.0320898840192375)),
 (88, np.float64(0.04050079673769965)),
 (89, np.float64(0.023460021872482063)),
 (90, np.float64(0.0)),
 (91, np.float64(0.02180723156474596)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0030782821766990325)),
 (94, np.float64(0.031577883403713716)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.002124513752074634)),
 (98, np.float64(0.004124088311897883)),
 (99, np.float64(0.009869131212049916)),
 (100, np.float64(0.0)),
 (101, np.float64(0.024901231167261013)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.013763528200689785)),
 (107, np.float64(0.0)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.01963575859372987)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.008023998974210972)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.009591791004678447)),
 (124, np.float64(0.0)),
 (125, np.float64(0.02227411083901458)),
 (126, np.float64(0.01507164480442525)),
 (127, np.float64(0.028953224382852638)),
 (128, np.float64(0.023078261586685845)),
 (129, np.float64(0.021123631164052324)),
 (130, np.float64(0.010830132720093089)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.00460964264959414)),
 (135, np.float64(0.0)),
 (136, np.float64(0.006588146246297217)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.034807985099722265)),
 (140, np.float64(0.0)),
 (141, np.float64(0.014646418376052964)),
 (142, np.float64(0.028492423146081185)),
 (143, np.float64(0.018074484890221513)),
 (144, np.float64(0.0)),
 (145, np.float64(0.010678263078813402)),
 (146, np.float64(0.033580485187203794)),
 (147, np.float64(0.00835478514837873)),
 (148, np.float64(0.005880350322225799)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.004697575389571579)),
 (152, np.float64(0.0)),
 (153, np.float64(0.0084414955782252)),
 (154, np.float64(0.00287538317679985)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.019855773026453652)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.013869560926683825)),
 (162, np.float64(0.0)),
 (163, np.float64(0.013902437605609452)),
 (164, np.float64(0.0)),
 (165, np.float64(0.014166541714544423)),
 (166, np.float64(0.0024723912789276032)),
 (167, np.float64(0.026187688042450138)),
 (168, np.float64(0.017745312096397473)),
 (169, np.float64(0.0016424826650705028)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0034461103691210354)),
 (173, np.float64(0.004392811468567792)),
 (174, np.float64(0.0063320998955734824)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.019584685794313387)),
 (179, np.float64(0.0)),
 (180, np.float64(0.02324591712581041)),
 (181, np.float64(0.0196356198119815)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.014435522705908853)),
 (186, np.float64(0.02444541552099091)),
 (187, np.float64(0.0)),
 (188, np.float64(0.02407752016637021)),
 (189, np.float64(0.020258179970566295)),
 (190, np.float64(0.032173472087778515)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.007214363022549967)),
 (194, np.float64(0.0)),
 (195, np.float64(0.004348996648649613)),
 (196, np.float64(0.010673940590591763)),
 (197, np.float64(0.0026432606624663575)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.027382653718254137)),
 (201, np.float64(0.023343019298938877)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.004848342766311163)),
 (205, np.float64(0.0)),
 (206, np.float64(0.003150693035795457)),
 (207, np.float64(0.008107438137600733)),
 (208, np.float64(0.014759020924372854)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0074774807817465155)),
 (211, np.float64(0.0017225913579550843)),
 (212, np.float64(0.0)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.016379610040267403)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0046173669638721075)),
 (219, np.float64(0.021157111911617017)),
 (220, np.float64(0.0)),
 (221, np.float64(0.018599401398695856)),
 (222, np.float64(0.007740824009677251)),
 (223, np.float64(0.0)),
 (224, np.float64(0.010588895898120546)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.011960564827476096)),
 (230, np.float64(0.02742831566844416)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.01622866053790436)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.03001845010896187)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0147304302876445)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.008159731079994646)),
 (244, np.float64(0.02268968190377181)),
 (245, np.float64(0.0)),
 (246, np.float64(0.00824129299642068)),
 (247, np.float64(0.0032235880447053643)),
 (248, np.float64(0.0)),
 (249, np.float64(0.015227202808502524)),
 (250, np.float64(0.0208278210835043)),
 (251, np.float64(0.014951712823299552)),
 (252, np.float64(0.0064093393949963395)),
 (253, np.float64(0.03001845010896187)),
 (254, np.float64(0.00557618096472887)),
 (255, np.float64(0.004965195878436835)),
 (256, np.float64(0.0020837810007003324)),
 (257, np.float64(0.0031560644742544457)),
 (258, np.float64(0.014925950751302373)),
 (259, np.float64(0.0)),
 (260, np.float64(0.014544315947659535)),
 (261, np.float64(0.0)),
 (262, np.float64(0.003187653878090688)),
 (263, np.float64(0.013542384926099193)),
 (264, np.float64(0.0)),
 (265, np.float64(0.009370317425616372)),
 (266, np.float64(0.0072248122546033355)),
 (267, np.float64(0.0)),
 (268, np.float64(0.019734694797795414)),
 (269, np.float64(0.0)),
 (270, np.float64(0.007810845784529397)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.017268376071205297)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.0022865087433872953)),
 (278, np.float64(0.007197943974031786)),
 (279, np.float64(0.02300388151302013)),
 (280, np.float64(0.002437503563887876)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.009392127305786506)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0030657462660518167)),
 (289, np.float64(0.007640400347333652)),
 (290, np.float64(0.005077389995298244)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.005782708714045112)),
 (296, np.float64(0.0)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.029924712706511692)),
 (300, np.float64(0.0)),
 (301, np.float64(0.022734754604940375)),
 (302, np.float64(0.012845234642088761)),
 (303, np.float64(0.0)),
 (304, np.float64(0.0114311213915134)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.0026197129585006744)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.01091093342192431)),
 (311, np.float64(0.011026834832756632)),
 (312, np.float64(0.0)),
 (313, np.float64(0.0)),
 (314, np.float64(0.009605292957563598)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.009779211589847547)),
 (318, np.float64(0.017977940661975965)),
 (319, np.float64(0.012677969202229975)),
 (320, np.float64(0.01494357655727523)),
 (321, np.float64(0.015485773409790663)),
 (322, np.float64(0.009705972668566158)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.02271872707351976)),
 (328, np.float64(0.06948520864378308)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.026914759282699246)),
 (332, np.float64(0.008422283059865346)),
 (333, np.float64(0.011778816142462508)),
 (334, np.float64(0.0)),
 (335, np.float64(0.005175791448587197)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.01333094467928718)),
 (340, np.float64(0.0)),
 (341, np.float64(0.013893705498837514)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.023227642315783968)),
 (345, np.float64(0.016563946928841236)),
 (346, np.float64(0.02499527963974398)),
 (347, np.float64(0.01938209242501062)),
 (348, np.float64(0.0)),
 (349, np.float64(0.015298692937768338)),
 (350, np.float64(0.004294258832110969)),
 (351, np.float64(0.009075365476943875)),
 (352, np.float64(0.0)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.0)),
 (357, np.float64(0.0124493799016967)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0021972127434444198)),
 (363, np.float64(0.0)),
 (364, np.float64(0.006463717553846421)),
 (365, np.float64(0.0068947547893193125)),
 (366, np.float64(0.005448923310699018)),
 (367, np.float64(0.027194445433751494)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.03440402835211617)),
 (372, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.03994945410523473)),
 (377, np.float64(0.019575883674058145)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.021879319802730196)),
 (381, np.float64(0.022948401206252952)),
 (382, np.float64(0.023657284576194287)),
 (383, np.float64(0.04520495080560537)),
 (384, np.float64(0.044391511368077195)),
 (385, np.float64(0.020509598544517144)),
 (386, np.float64(0.08024171549608934)),
 (387, np.float64(0.0819066191249451)),
 (388, np.float64(0.014074221420297729)),
 (389, np.float64(0.01156829607322948)),
 (390, np.float64(0.004098062386879047)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.02259264396501823)),
 (395, np.float64(0.016637349792977065)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.022569904811670684)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0030972707638411163)),
 (401, np.float64(0.005780878695521852)),
 (402, np.float64(0.005132331134583698)),
 (403, np.float64(0.006476600013746463)),
 (404, np.float64(0.0)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.03001845010896187)),
 (409, np.float64(0.0172850328067368)),
 (410, np.float64(0.011799697795756863)),
 (411, np.float64(0.014120690794919922)),
 (412, np.float64(0.012286626875190628)),
 (413, np.float64(0.032113501988870044)),
 (414, np.float64(0.02444071586454471)),
 (415, np.float64(0.04595169661788638)),
 (416, np.float64(0.03700500363949519)),
 (417, np.float64(0.0)),
 (418, np.float64(0.02065463334507915)),
 (419, np.float64(0.009137459445981443)),
 (420, np.float64(0.012730478213370828)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0032979799955424475)),
 (424, np.float64(0.0)),
 (425, np.float64(0.00512261445229682)),
 (426, np.float64(0.0)),
 (427, np.float64(0.010406842140857415)),
 (428, np.float64(0.026842879250297474)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.015102289765436523)),
 (434, np.float64(0.015213332103016498)),
 (435, np.float64(0.004342307145560978)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.016388164350644153)),
 (440, np.float64(0.0)),
 (441, np.float64(0.022947806652170725)),
 (442, np.float64(0.004800379039447179)),
 (443, np.float64(0.024910941639351612)),
 (444, np.float64(0.0)),
 (445, np.float64(0.04183181711602073)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.00297585691241289)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.013279752391352007)),
 (455, np.float64(0.007076572567583822)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.006418867332576837)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.01970015143428707)),
 (470, np.float64(0.021337067675705673)),
 (471, np.float64(0.013775012153961642)),
 (472, np.float64(0.019669730371413896)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.03341225082623925)),
 (476, np.float64(0.02475180988173646)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.01810413421613658)),
 (480, np.float64(0.009662890015353151)),
 (481, np.float64(0.043943585765211124)),
 (482, np.float64(0.001445676672534338)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.020205135189134426)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.02264772722321082)),
 (489, np.float64(0.021628811404938407)),
 (490, np.float64(0.0)),
 (491, np.float64(0.0)),
 (492, np.float64(0.005334330832631217)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.010587020167205525)),
 (496, np.float64(0.020268707327932324)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0)),
 (499, np.float64(0.011372233571206366)),
 (500, np.float64(0.0)),
 (501, np.float64(0.005130194370818888)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0013627881473615574)),
 (505, np.float64(0.0)),
 (506, np.float64(0.02335456994381423)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.010153393962379964)),
 (510, np.float64(0.01877858481035832)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.010034781209449886)),
 (515, np.float64(0.0)),
 (516, np.float64(0.009140186901715206)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.009207513780446918)),
 (520, np.float64(0.0)),
 (521, np.float64(0.013875269407272035)),
 (522, np.float64(0.0)),
 (523, np.float64(0.017491979234640326)),
 (524, np.float64(0.026029500250742063)),
 (525, np.float64(0.03029004563526326)),
 (526, np.float64(0.008423776184001952)),
 (527, np.float64(0.01813326617328362)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.022599999706723117)),
 (533, np.float64(0.016625592366082086)),
 (534, np.float64(0.03350031116223012)),
 (535, np.float64(0.046016983033189504)),
 (536, np.float64(0.027364677324737106)),
 (537, np.float64(0.02374947458102507)),
 (538, np.float64(0.010690373958996692)),
 (539, np.float64(0.03747920629696514)),
 (540, np.float64(0.022479043198673533)),
 (541, np.float64(0.0)),
 (542, np.float64(0.009132137766841828)),
 (543, np.float64(0.0235100379402279)),
 (544, np.float64(0.0)),
 (545, np.float64(0.027969999472758716)),
 (546, np.float64(0.0)),
 (547, np.float64(0.03497402879708919)),
 (548, np.float64(0.009840649797829074)),
 (549, np.float64(0.015264173364887827)),
 (550, np.float64(0.018104719837678605)),
 (551, np.float64(0.013744456253425404)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.00694369881807455)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.035966086901001046)),
 (558, np.float64(0.013289960870115658)),
 (559, np.float64(0.0)),
 (560, np.float64(0.009152786245938965)),
 (561, np.float64(0.0)),
 (562, np.float64(0.042686197170836916)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.008879635709481342)),
 (566, np.float64(0.004785499419698542)),
 (567, np.float64(0.0)),
 (568, np.float64(0.024903274905888593)),
 (569, np.float64(0.017552108899483748)),
 (570, np.float64(0.0)),
 (571, np.float64(0.006963661731280012)),
 (572, np.float64(0.0157590761800748)),
 (573, np.float64(0.0036175474357959445)),
 (574, np.float64(0.0)),
 (575, np.float64(0.003914020861400064)),
 (576, np.float64(0.04509875169324787)),
 (577, np.float64(0.011402413552619473)),
 (578, np.float64(0.025044722875722934)),
 (579, np.float64(0.016389676484386814)),
 (580, np.float64(0.0)),
 (581, np.float64(0.006943886646890642)),
 (582, np.float64(0.0)),
 (583, np.float64(0.008124354535867677)),
 (584, np.float64(0.009511243190721467)),
 (585, np.float64(0.04340206604607845)),
 (586, np.float64(0.007371934495256454)),
 (587, np.float64(0.014939275053680905)),
 (588, np.float64(0.0)),
 (589, np.float64(0.02411322782898219)),
 (590, np.float64(0.004869095920834748)),
 (591, np.float64(0.007941275793145162)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.02550353701784512)),
 (595, np.float64(0.0)),
 (596, np.float64(0.006180133389718298)),
 (597, np.float64(0.01497631110996746)),
 (598, np.float64(0.0)),

In [13]:
def sort_des(idx_array):
    sorted_array = sorted(idx_array, key=lambda x: x[1], reverse=True)
    return sorted_array[1:11]

sorted_array = sort_des(idx_array=book_idx)
sorted_array

[(15012, np.float64(0.24589210593098956)),
 (13832, np.float64(0.23351932819036458)),
 (23708, np.float64(0.21726205019158973)),
 (17247, np.float64(0.19808039887633125)),
 (5935, np.float64(0.1928198579378127)),
 (6879, np.float64(0.1902891339739173)),
 (40495, np.float64(0.1855343589573354)),
 (16360, np.float64(0.18507251253371887)),
 (24499, np.float64(0.17768651312078693)),
 (39114, np.float64(0.1765154404979708))]

# Get the book names from the indices

In [14]:
sorted_array[1:6]

[(13832, np.float64(0.23351932819036458)),
 (23708, np.float64(0.21726205019158973)),
 (17247, np.float64(0.19808039887633125)),
 (5935, np.float64(0.1928198579378127)),
 (6879, np.float64(0.1902891339739173))]

In [15]:
def get_book_name(rec_books):
    rec_books_info = []
    for i in rec_books:
        
        rec_books_info.append(df.iloc[i[0], :])
        
    return pd.DataFrame(rec_books_info)

result = get_book_name(sorted_array)
# result = pd.DataFrame(result)
result

,Id,Name,Authors,Rating,Description
15012,727604,The Soul Beneath the Skin: The Unseen Hearts a...,David Nimmons,3.88,surprise think provoke book begin obvious fact...
13832,725500,Life Outside: The Signorile Report on Gay Men:...,Michelangelo Signorile,3.68,strong popular em em magazine columnist michel...
23708,743801,Lavender Culture,Karla Jay,3.55,influence gays lesbians language literature th...
17247,731667,Queer Wars: The New Gay Right and Its Critics,Paul A. Robinson,4.05,rebellion stonewall recent battle sex marriage...
5935,710934,Gay by the Bay: A History of Queer Culture in ...,Susan Stryker,3.89,fabulous montage word image first book ever ch...
6879,712601,Art and Sex in Greenwich Village: A Memoir of ...,Felice Picano,3.82,decade stonewall rebellions small gay press na...
40495,774575,Gay Men at the Millennium,Michael Lowenthal,4.40,core issue face gay community close millennium...
16360,730029,"If You Seduce a Straight Person, Can You Make ...",John P. De Cecco,4.00,debate whether people bear homosexual biologic...
24499,745249,Artificial Intelligence and Human Reason: A Te...,Joseph F. Rychlak,4.00,author acclaim gay fiction speak bring us new ...
39114,772020,John Gay and the London Theatre,Calhoun Winton,3.00,beggar opera often refer today first musical c...

# Put everything together

In [33]:
def get_rec_books(book_idx, df):
    selected_book = df.iloc[book_idx:book_idx+1, :]
    data = preprocess_dataframe(df=df, column_name='Description')
    matrix = get_text_feature(data)
    book_sim = calculate_cosine_similarity_of_a_target_book(book=matrix[book_idx], tfidf_matrix=matrix)
    book_sim = add_indices(book_sim)
    book_sim = sort_des(book_sim)
    result = get_book_name(rec_books=book_sim)
    
    return selected_book, result

selected_book, rec_books = get_rec_books(df=df, book_idx=1000)

In [34]:
rec_books

,Id,Name,Authors,Rating,Description
1,700002,Culture Keepers-Florida: Oral History of the A...,Deborah Johnson-Simon,0.00,
2,700003,Holiday Favorites: The Best of the Williams-So...,Allen Rosenberg,4.55,collector edition feature fabulous full color ...
3,700004,"Soups, Salads & Starters: the Best of Williams...",Allan Rosenberg,4.70,
4,700005,Breakfasts & Brunches,Time-Life Books,3.88,america respect cookware retailer world larges...
5,700006,Vegetarian (Best of Williams-Sonoma Kitchen Li...,Allan Rosenberg,4.18,williams sonoma almost vegetarian present reci...
6,700007,Pork and Lamb,Joanne Weir,4.00,america respect cookware retailer world larges...
7,700008,Ice Creams and Sorbets,Sarah Tenaglia,3.00,must collection kitchen america respect cookwa...
8,700011,Paradise/Tender Triumph (Omnibus),Judith McNaught,4.31,together last two acclaim novels danger desire...
9,700015,50 Thrifty Maui Restaurants: Dining on a Budge...,Yvonne Biegel,3.50,unique guidebook great food bargain price ocea...
10,700017,Frommer's Maui Day by Day,Jeanette Foster,4.14,attractively price four color guide offer doze...

In [35]:
selected_book = pd.DataFrame(selected_book)
selected_book

,Id,Name,Authors,Rating,Description
1000,701907,"Diary of a Slave Girl, Ruby Jo",K.J. McWilliams,4.26,

In [36]:
print(f"Selected book: '{selected_book['Name'].iloc[0]}'\n")
for name in rec_books['Name']: 
    print(f"{name}")

Selected book: 'Diary of a Slave Girl, Ruby Jo'

Culture Keepers-Florida: Oral History of the African American Museum Experience
Holiday Favorites: The Best of the Williams-Sonoma Kitchen Library
Soups, Salads & Starters: the Best of Williams-Sonoma Kitchen Library
Breakfasts & Brunches
Vegetarian (Best of Williams-Sonoma Kitchen Library)
Pork and Lamb
Ice Creams and Sorbets
Paradise/Tender Triumph (Omnibus)
50 Thrifty Maui Restaurants: Dining on a Budget, Island-Style
Frommer's Maui Day by Day