# Import libraries

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Get the data

In [ ]:
# Load the dataset from the CSV file
dataset = pd.read_csv('../data/book700k-800k.csv')
df = pd.DataFrame({'Id': dataset['Id'],
                        'Name': dataset['Name'],
                        'Authors': dataset['Authors'],
                        'Publish year': dataset['PublishYear'],
                        'Rating': dataset['Rating'],
                        'Description': dataset['Description']})
df['Text feature'] = (df['Authors'].fillna('') + ' ' +
                      df['Name'].fillna('') + ' ' +
                      df['Description'].fillna('') +
                      df['Description'].fillna(''))

# Display the first few rows of the dataset
df.head

<bound method NDFrame.head of            Id                                               Name  \
0      700000  A Passion to Preserve: Gay Men as Keepers of C...
1      700002  Culture Keepers-Florida: Oral History of the A...
2      700003  Holiday Favorites: The Best of the Williams-So...
3      700004  Soups, Salads & Starters: the Best of Williams...
4      700005                              Breakfasts & Brunches
...       ...                                                ...
54268  799991           Piano Concerto Highlights for Solo Piano
54269  799993  Noggin King of the Nogs (The Sagas of Noggin t...
54270  799994  No Greater Glory: The Four Immortal Chaplains ...
54271  799996  The White Company by Arthur Conan Doyle, Ficti...
54272  799997                    Livewire Real Lives Dawn Fraser

                     Authors  Publish year  Rating  \
0               Will Fellows          2005    3.75
1      Deborah Johnson-Simon          2006    0.00
2            Allen Rosenberg          2004    4.55
3            Allan Rosenberg          2004    4.70
4            Time-Life Books          1997    3.88
...                      ...           ...     ...
54268         Felix Guenther          2006    5.00
54269        Oliver Postgate          2001    4.38
54270            Dan Kurzman          2005    4.02
54271     Arthur Conan Doyle          2004    3.89
54272            Ian Jackson          2000    0.00

                                             Description  \
0      From large cities to rural communities, gay me...
1                                                    NaN
2      This collector's edition features fabulous ful...
3                                                    NaN
4      America's most respected cookware retailer, th...
...                                                  ...
54268  Concertos are every pianist's pinnacle of perf...
54269  1. King of the Nogs --<br />2. The ice dragon ...
54270  The sinking of the <i>Dorchester</i> in the ic...
54271  "By my hilt!" cried the other, "if you were to...
54272  This book tells the story of Dawn Fraser, vote...

                                            Text feature
0      Will Fellows A Passion to Preserve: Gay Men as...
1      Deborah Johnson-Simon Culture Keepers-Florida:...
2      Allen Rosenberg Holiday Favorites: The Best of...
3      Allan Rosenberg Soups, Salads & Starters: the ...
4      Time-Life Books Breakfasts & Brunches America'...
...                                                  ...
54268  Felix Guenther Piano Concerto Highlights for S...
54269  Oliver Postgate Noggin King of the Nogs (The S...
54270  Dan Kurzman No Greater Glory: The Four Immorta...
54271  Arthur Conan Doyle The White Company by Arthur...
54272  Ian Jackson Livewire Real Lives Dawn Fraser Th...

[54273 rows x 7 columns]>

In [72]:
df['Text feature'][0]

'Will Fellows A Passion to Preserve: Gay Men as Keepers of Culture From large cities to rural communities, gay men have long been impassioned pioneers as keepers of culture: rescuing and restoring decrepit buildings, revitalizing blighted neighborhoods, saving artifacts and documents of historical significance. <i>A Passion to Preserve</i> explores this authentic and complex dimension of gay men’s lives by profiling early and contemporary preservationists from throughout the United States, highlighting contributions to the larger culture that gays are exceptionally inclined to make.'

In [73]:
# Replace Nan values with ''
df['Description'] = df['Description'].fillna('')
ori_description = df['Description']

In [74]:
df['Description'][0]

'From large cities to rural communities, gay men have long been impassioned pioneers as keepers of culture: rescuing and restoring decrepit buildings, revitalizing blighted neighborhoods, saving artifacts and documents of historical significance. <i>A Passion to Preserve</i> explores this authentic and complex dimension of gay men’s lives by profiling early and contemporary preservationists from throughout the United States, highlighting contributions to the larger culture that gays are exceptionally inclined to make.'

# Data preprocessing

In [75]:
import re
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Initialize the stopwords
stop_words = set(stopwords.words('english'))

def preprocessing_text(text):
    # Convert the input text to string
    text = str(text)
    
    # Convert text to lowercase
    text = text.lower()
    
    # Remove special characters and digits and replace them with a spcae
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    
    # Tokenize the text
    tokens = nltk.word_tokenize(text)
    
    # Remove stop words
    tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatize the tokens (convert words into their base dictionary form, ex. cats->cat)
    tokens = [lemmatizer.lemmatize(word, pos='v') for word in tokens]
    
    # Return the processed text as a string
    return " ".join(tokens)


def preprocess_dataframe(df, column_name):
    df[column_name]= df[column_name].apply(preprocessing_text)
    return df

df = preprocess_dataframe(df=df, column_name='Description')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [76]:
df['Description'].head

<bound method NDFrame.head of 0        large cities rural communities gay men long im...
1
2        collector edition feature fabulous full color ...
3
4        america respect cookware retailer world larges...
                               ...
54268    concertos every pianist pinnacle performance r...
54269    king nogs br ice dragon br fly machine br omru...
54270    sink dorchester icy water greenland shortly mi...
54271    hilt cry cross narrow sea would find thick be ...
54272    book tell story dawn fraser vote greatest fema...
Name: Description, Length: 54273, dtype: str>

# Get text features using tf-idf

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer

def get_text_feature(df):
    text_features = df['Text feature']
    # Text feature
    tfidf = TfidfVectorizer(stop_words="english",
                            strip_accents='ascii',
                            token_pattern=r'\w+')

    tfidf_matrix = tfidf.fit_transform(text_features)
    tfidf.get_feature_names_out()
    
    return tfidf_matrix
tfidf_matrix = get_text_feature(df=df)

# Calculate cosine similarity
`from sklearn.metrics.pairwise import cosine_similarity`

In [78]:
from sklearn.metrics.pairwise import cosine_similarity

def calculate_cosine_similarity_of_a_target_book(book, tfidf_matrix):
    """Calculate the cosine similarity between a target book and all books
    in the TF-IDF matrix.

    Args:
        book (scipy.sparse.csr_matrix): 
            A single TF-IDF row vector representing the target book.
            Shape should be (1, n_features).
        tfidf_matrix (scipy.sparse.csr_matrix_): 
            TF-IDF matrix containing all book vectors.
            Shape should be (n_books, n_features).

    Returns:
        numpy.ndarray: A 2D array containing cosine similarity scores between the target book and 
        every book in the TF-IDF matrix.
        Shape will be (1, n_books).
    """
    X = book
    Y = tfidf_matrix
    cs = cosine_similarity(X, Y)
    return cs

book = calculate_cosine_similarity_of_a_target_book(tfidf_matrix=tfidf_matrix, book=tfidf_matrix[0])
book

array([[1.        , 0.1759361 , 0.        , ..., 0.01665048, 0.        ,
        0.01377254]], shape=(1, 54273))

# Add indices to the similarity array

In [79]:
tfidf_matrix.shape[0]

54273

In [80]:
def add_indices(sim_array):
    indexed_array = []
    for i, s in zip(range(tfidf_matrix.shape[0]), sim_array[0]):
        indexed_array.append((i, s))
    return indexed_array
    
book_idx = add_indices(book)
book_idx

[(0, np.float64(1.0000000000000004)),
 (1, np.float64(0.1759361010966507)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(0.0)),
 (5, np.float64(0.004362876508365917)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.02618616693317984)),
 (9, np.float64(0.003625613727191063)),
 (10, np.float64(0.004785675674866886)),
 (11, np.float64(0.002029077582183373)),
 (12, np.float64(0.027821324639495902)),
 (13, np.float64(0.031798158817712134)),
 (14, np.float64(0.019411515560834834)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0025114041824299653)),
 (19, np.float64(0.013737418330807183)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.029205883127773797)),
 (23, np.float64(0.0)),
 (24, np.float64(0.025214664716739867)),
 (25, np.float64(0.013690511806384871)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.0)),
 (31, np.float64(0.004357262278194984)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.0)),
 (36, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.008486802265867305)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.0)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.003135111010162695)),
 (50, np.float64(0.0)),
 (51, np.float64(0.005685163333530823)),
 (52, np.float64(0.014775035342854438)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.016369576034599348)),
 (56, np.float64(0.0)),
 (57, np.float64(0.008706287598767664)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.007037540085369776)),
 (61, np.float64(0.0049335047694593435)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.005373219473204176)),
 (65, np.float64(0.0)),
 (66, np.float64(0.012017577090677902)),
 (67, np.float64(0.0)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.00619006135858368)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.003188942702401238)),
 (75, np.float64(0.004610260633829279)),
 (76, np.float64(0.01034699118321769)),
 (77, np.float64(0.03148214820089522)),
 (78, np.float64(0.008014495681679439)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.016632173899098067)),
 (83, np.float64(0.0)),
 (84, np.float64(0.010714444320869059)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.013962585982068624)),
 (88, np.float64(0.02142528832412961)),
 (89, np.float64(0.00794114877905627)),
 (90, np.float64(0.013228124582586107)),
 (91, np.float64(0.0)),
 (92, np.float64(0.01980494543771435)),
 (93, np.float64(0.0035782488758709648)),
 (94, np.float64(0.019317022312297295)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.004260525672767283)),
 (99, np.float64(0.007194653873453892)),
 (100, np.float64(0.0)),
 (101, np.float64(0.011606245184690642)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.008098347792433668)),
 (107, np.float64(0.0)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.01588981188181368)),
 (113, np.float64(0.0)),
 (114, np.float64(0.00629415300657819)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.007854144511567539)),
 (124, np.float64(0.0)),
 (125, np.float64(0.014625606288232625)),
 (126, np.float64(0.011718535699911136)),
 (127, np.float64(0.014811282771947272)),
 (128, np.float64(0.0)),
 (129, np.float64(0.01266150658925735)),
 (130, np.float64(0.012280382685183973)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.004710489401885682)),
 (135, np.float64(0.014418077822970332)),
 (136, np.float64(0.004926219785169423)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.01984295462944147)),
 (140, np.float64(0.0)),
 (141, np.float64(0.012099290409530785)),
 (142, np.float64(0.018740307794912692)),
 (143, np.float64(0.011823935171288085)),
 (144, np.float64(0.0)),
 (145, np.float64(0.008027092215537594)),
 (146, np.float64(0.01705145960278978)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0059946313978131455)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.003288677283643961)),
 (152, np.float64(0.0)),
 (153, np.float64(0.005628981125622176)),
 (154, np.float64(0.003236894471958959)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.013134814984401359)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.0069388349872309685)),
 (162, np.float64(0.0)),
 (163, np.float64(0.01243885380831795)),
 (164, np.float64(0.0)),
 (165, np.float64(0.008928485698854816)),
 (166, np.float64(0.0026147894854194496)),
 (167, np.float64(0.0)),
 (168, np.float64(0.011108659156791743)),
 (169, np.float64(0.0)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0023628111182599333)),
 (173, np.float64(0.0)),
 (174, np.float64(0.0)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.01321866925587233)),
 (179, np.float64(0.0)),
 (180, np.float64(0.015319501236986208)),
 (181, np.float64(0.019062458270087172)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.006087557839368999)),
 (186, np.float64(0.022402418793809338)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.018236478568036698)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.00502495768053034)),
 (194, np.float64(0.0)),
 (195, np.float64(0.001863002705476742)),
 (196, np.float64(0.008600963866945768)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.01802722395409921)),
 (201, np.float64(0.01670653488368448)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.004550626310168712)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.005101013106047651)),
 (208, np.float64(0.005416874434647647)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (212, np.float64(0.0)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.01522274685487474)),
 (216, np.float64(0.0)),
 (217, np.float64(0.039872241064626404)),
 (218, np.float64(0.004112034777997874)),
 (219, np.float64(0.014218731112563738)),
 (220, np.float64(0.0)),
 (221, np.float64(0.01135938965707746)),
 (222, np.float64(0.005943291517007921)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0082221852206939)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.0025373443221215946)),
 (230, np.float64(0.012465490733359917)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.01630588279538204)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.03176572025069503)),
 (240, np.float64(0.010367656083002372)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.006072289307671936)),
 (244, np.float64(0.012828301574596)),
 (245, np.float64(0.0)),
 (246, np.float64(0.005058634203393212)),
 (247, np.float64(0.0)),
 (248, np.float64(0.0)),
 (249, np.float64(0.0)),
 (250, np.float64(0.018422746732442638)),
 (251, np.float64(0.005447490063568988)),
 (252, np.float64(0.006061728136720759)),
 (253, np.float64(0.0)),
 (254, np.float64(0.0)),
 (255, np.float64(0.0)),
 (256, np.float64(0.0)),
 (257, np.float64(0.0)),
 (258, np.float64(0.013274012995772055)),
 (259, np.float64(0.0)),
 (260, np.float64(0.009467001824676791)),
 (261, np.float64(0.0)),
 (262, np.float64(0.0035115345545975135)),
 (263, np.float64(0.0051034724054053165)),
 (264, np.float64(0.0)),
 (265, np.float64(0.006063387360010476)),
 (266, np.float64(0.0)),
 (267, np.float64(0.0)),
 (268, np.float64(0.006976794687272658)),
 (269, np.float64(0.0)),
 (270, np.float64(0.006637304005723933)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.005900232625038147)),
 (278, np.float64(0.0026723140601167187)),
 (279, np.float64(0.012740212081894582)),
 (280, np.float64(0.0)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.005912225557948146)),
 (288, np.float64(0.0035714751506568452)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0032421453355610643)),
 (291, np.float64(0.0)),
 (292, np.float64(0.05727954688516983)),
 (293, np.float64(0.016596284724880346)),
 (294, np.float64(0.0)),
 (295, np.float64(0.0)),
 (296, np.float64(0.0)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.023210422359585904)),
 (300, np.float64(0.0)),
 (301, np.float64(0.010652723183442701)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.007435264997291652)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.006748678719965006)),
 (311, np.float64(0.006948541850236991)),
 (312, np.float64(0.0)),
 (313, np.float64(0.0)),
 (314, np.float64(0.005980466732601246)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.01964459284103381)),
 (319, np.float64(0.008024534467967075)),
 (320, np.float64(0.015517816736162492)),
 (321, np.float64(0.010195583596528814)),
 (322, np.float64(0.003178343558168737)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.010108705430220268)),
 (328, np.float64(0.05311145310957436)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.014914825243391789)),
 (332, np.float64(0.006798114170382386)),
 (333, np.float64(0.0)),
 (334, np.float64(0.0)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0069386837726103925)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.015191878885034281)),
 (345, np.float64(0.0206760412085687)),
 (346, np.float64(0.024449983927282225)),
 (347, np.float64(0.009589945284158236)),
 (348, np.float64(0.0)),
 (349, np.float64(0.012795179436589251)),
 (350, np.float64(0.0)),
 (351, np.float64(0.00330968496851363)),
 (352, np.float64(0.0)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.0)),
 (357, np.float64(0.008267898381873891)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0)),
 (363, np.float64(0.0)),
 (364, np.float64(0.0)),
 (365, np.float64(0.010998064093816297)),
 (366, np.float64(0.0)),
 (367, np.float64(0.007210194441079518)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.03259798795482715)),
 (372, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.03526354259620173)),
 (377, np.float64(0.01937286729691708)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.01910317889489363)),
 (381, np.float64(0.030187708217876807)),
 (382, np.float64(0.04790774256075744)),
 (383, np.float64(0.043867079026466235)),
 (384, np.float64(0.048461178189764746)),
 (385, np.float64(0.03455851684253136)),
 (386, np.float64(0.08771937706588034)),
 (387, np.float64(0.08068547552307254)),
 (388, np.float64(0.009542561409583122)),
 (389, np.float64(0.00824982153318222)),
 (390, np.float64(0.004257996914081042)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.018316016554710247)),
 (395, np.float64(0.014397264799521723)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.009278779729985816)),
 (399, np.float64(0.0)),
 (400, np.float64(0.002143633688496597)),
 (401, np.float64(0.0)),
 (402, np.float64(0.003541576929069753)),
 (403, np.float64(0.006246351827402825)),
 (404, np.float64(0.0)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.0)),
 (409, np.float64(0.004788725485694456)),
 (410, np.float64(0.00878223760051153)),
 (411, np.float64(0.009387421403079865)),
 (412, np.float64(0.0076221129980028795)),
 (413, np.float64(0.018000398597317405)),
 (414, np.float64(0.025829434366243718)),
 (415, np.float64(0.0074377157539966526)),
 (416, np.float64(0.01765842902178651)),
 (417, np.float64(0.0)),
 (418, np.float64(0.014883233263546078)),
 (419, np.float64(0.00620565068896807)),
 (420, np.float64(0.006218996134472146)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.004298991987737779)),
 (426, np.float64(0.0)),
 (427, np.float64(0.007785994708731734)),
 (428, np.float64(0.013850543776355556)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.010517159069115763)),
 (434, np.float64(0.017792614031358227)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.009876289834308005)),
 (440, np.float64(0.0)),
 (441, np.float64(0.013899314496173976)),
 (442, np.float64(0.005038851922345142)),
 (443, np.float64(0.01453777231721731)),
 (444, np.float64(0.0)),
 (445, np.float64(0.023048228232332275)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.003293045974681017)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.0033666152246191036)),
 (455, np.float64(0.0)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0052466350187104415)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.009366493939081786)),
 (470, np.float64(0.011792897858782686)),
 (471, np.float64(0.0)),
 (472, np.float64(0.005029595930868163)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.037644228710129825)),
 (476, np.float64(0.025227815384091645)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.020246183164721085)),
 (480, np.float64(0.019556776923365785)),
 (481, np.float64(0.04187268415529162)),
 (482, np.float64(0.0015438558149316484)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.008923067865238209)),
 (489, np.float64(0.01180761679274233)),
 (490, np.float64(0.0)),
 (491, np.float64(0.0)),
 (492, np.float64(0.004134805827897953)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.004480443384514841)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0)),
 (499, np.float64(0.00900732935543386)),
 (500, np.float64(0.0)),
 (501, np.float64(0.003648998668308832)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.009872076176134352)),
 (505, np.float64(0.0)),
 (506, np.float64(0.015715304344789238)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.010147977936916658)),
 (510, np.float64(0.007818610156771103)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.013150291481804627)),
 (515, np.float64(0.0)),
 (516, np.float64(0.0068471265857282)),
 (517, np.float64(0.0201803021695919)),
 (518, np.float64(0.0)),
 (519, np.float64(0.010334242272002806)),
 (520, np.float64(0.0)),
 (521, np.float64(0.009979251756712267)),
 (522, np.float64(0.0)),
 (523, np.float64(0.01210161281332153)),
 (524, np.float64(0.024727304148580195)),
 (525, np.float64(0.02936753322855205)),
 (526, np.float64(0.007098585900162209)),
 (527, np.float64(0.005717524880201846)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.02040687236443465)),
 (533, np.float64(0.012025662746418548)),
 (534, np.float64(0.03272295709517777)),
 (535, np.float64(0.04142003234113253)),
 (536, np.float64(0.030037477651193707)),
 (537, np.float64(0.02331026202872228)),
 (538, np.float64(0.008808942202620462)),
 (539, np.float64(0.0192753822234788)),
 (540, np.float64(0.013016202963907072)),
 (541, np.float64(0.0)),
 (542, np.float64(0.007103501704491174)),
 (543, np.float64(0.012148123109800239)),
 (544, np.float64(0.0)),
 (545, np.float64(0.020087785176954483)),
 (546, np.float64(0.0)),
 (547, np.float64(0.025048888556652753)),
 (548, np.float64(0.0091828661292723)),
 (549, np.float64(0.008169903633949734)),
 (550, np.float64(0.0048691800929089165)),
 (551, np.float64(0.008733249229186894)),
 (552, np.float64(0.0)),
 (553, np.float64(0.023991344874062414)),
 (554, np.float64(0.006010384351080899)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.034697413119942094)),
 (558, np.float64(0.010799751809734786)),
 (559, np.float64(0.0)),
 (560, np.float64(0.004428737865943228)),
 (561, np.float64(0.0)),
 (562, np.float64(0.03340805061998169)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.005142764652632)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.016331834064826526)),
 (569, np.float64(0.007774489353442283)),
 (570, np.float64(0.0)),
 (571, np.float64(0.0)),
 (572, np.float64(0.021002071259172077)),
 (573, np.float64(0.0)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.013379819476204476)),
 (577, np.float64(0.006077086777791235)),
 (578, np.float64(0.017059522992135326)),
 (579, np.float64(0.01122300509703132)),
 (580, np.float64(0.0)),
 (581, np.float64(0.0)),
 (582, np.float64(0.0)),
 (583, np.float64(0.009078696910692397)),
 (584, np.float64(0.00571820970965813)),
 (585, np.float64(0.02383646153156262)),
 (586, np.float64(0.009648078711772904)),
 (587, np.float64(0.011040856469812205)),
 (588, np.float64(0.0)),
 (589, np.float64(0.007527086919235615)),
 (590, np.float64(0.004659015414491124)),
 (591, np.float64(0.00605835425524422)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.016995657647048364)),
 (595, np.float64(0.0)),
 (596, np.float64(0.0038835856848075615)),
 (597, np.float64(0.010365226215233657)),
 (598, np.float64(0.0)),
 (599, np.float64(0.0)),
 (600, np.float64(0.007765131764317479)),
 (601, np.float64(0.0)),
 (602, np.float64(0.041268180905428845)),
 (603, np.float64(0.013099317102805194)),
 (604, np.float64(0.025097703180889514)),
 (605, np.float64(0.0)),
 (606, np.float64(0.006436680038535129)),
 (607, np.float64(0.0)),
 (608, np.float64(0.0)),
 (609, np.float64(0.0)),
 (610, np.float64(0.002888088999563761)),
 (611, np.float64(0.012284878655846373)),
 (612, np.float64(0.0048397265435296734)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.004137156210366609)),
 (616, np.float64(0.022134291077993293)),
 (617, np.float64(0.008162005960723757)),
 (618, np.float64(0.005308591237628957)),
 (619, np.float64(0.0)),
 (620, np.float64(0.0)),

# Sort descendent

In [81]:
book_idx

[(0, np.float64(1.0000000000000004)),
 (1, np.float64(0.1759361010966507)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(0.0)),
 (5, np.float64(0.004362876508365917)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.02618616693317984)),
 (9, np.float64(0.003625613727191063)),
 (10, np.float64(0.004785675674866886)),
 (11, np.float64(0.002029077582183373)),
 (12, np.float64(0.027821324639495902)),
 (13, np.float64(0.031798158817712134)),
 (14, np.float64(0.019411515560834834)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0025114041824299653)),
 (19, np.float64(0.013737418330807183)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.029205883127773797)),
 (23, np.float64(0.0)),
 (24, np.float64(0.025214664716739867)),
 (25, np.float64(0.013690511806384871)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.0)),
 (31, np.float64(0.004357262278194984)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.0)),
 (36, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.008486802265867305)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.0)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.003135111010162695)),
 (50, np.float64(0.0)),
 (51, np.float64(0.005685163333530823)),
 (52, np.float64(0.014775035342854438)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.016369576034599348)),
 (56, np.float64(0.0)),
 (57, np.float64(0.008706287598767664)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.007037540085369776)),
 (61, np.float64(0.0049335047694593435)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.005373219473204176)),
 (65, np.float64(0.0)),
 (66, np.float64(0.012017577090677902)),
 (67, np.float64(0.0)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.00619006135858368)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.003188942702401238)),
 (75, np.float64(0.004610260633829279)),
 (76, np.float64(0.01034699118321769)),
 (77, np.float64(0.03148214820089522)),
 (78, np.float64(0.008014495681679439)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.016632173899098067)),
 (83, np.float64(0.0)),
 (84, np.float64(0.010714444320869059)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.013962585982068624)),
 (88, np.float64(0.02142528832412961)),
 (89, np.float64(0.00794114877905627)),
 (90, np.float64(0.013228124582586107)),
 (91, np.float64(0.0)),
 (92, np.float64(0.01980494543771435)),
 (93, np.float64(0.0035782488758709648)),
 (94, np.float64(0.019317022312297295)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.004260525672767283)),
 (99, np.float64(0.007194653873453892)),
 (100, np.float64(0.0)),
 (101, np.float64(0.011606245184690642)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.008098347792433668)),
 (107, np.float64(0.0)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.01588981188181368)),
 (113, np.float64(0.0)),
 (114, np.float64(0.00629415300657819)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.007854144511567539)),
 (124, np.float64(0.0)),
 (125, np.float64(0.014625606288232625)),
 (126, np.float64(0.011718535699911136)),
 (127, np.float64(0.014811282771947272)),
 (128, np.float64(0.0)),
 (129, np.float64(0.01266150658925735)),
 (130, np.float64(0.012280382685183973)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.004710489401885682)),
 (135, np.float64(0.014418077822970332)),
 (136, np.float64(0.004926219785169423)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.01984295462944147)),
 (140, np.float64(0.0)),
 (141, np.float64(0.012099290409530785)),
 (142, np.float64(0.018740307794912692)),
 (143, np.float64(0.011823935171288085)),
 (144, np.float64(0.0)),
 (145, np.float64(0.008027092215537594)),
 (146, np.float64(0.01705145960278978)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0059946313978131455)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.003288677283643961)),
 (152, np.float64(0.0)),
 (153, np.float64(0.005628981125622176)),
 (154, np.float64(0.003236894471958959)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.013134814984401359)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.0069388349872309685)),
 (162, np.float64(0.0)),
 (163, np.float64(0.01243885380831795)),
 (164, np.float64(0.0)),
 (165, np.float64(0.008928485698854816)),
 (166, np.float64(0.0026147894854194496)),
 (167, np.float64(0.0)),
 (168, np.float64(0.011108659156791743)),
 (169, np.float64(0.0)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0023628111182599333)),
 (173, np.float64(0.0)),
 (174, np.float64(0.0)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.01321866925587233)),
 (179, np.float64(0.0)),
 (180, np.float64(0.015319501236986208)),
 (181, np.float64(0.019062458270087172)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.006087557839368999)),
 (186, np.float64(0.022402418793809338)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.018236478568036698)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.00502495768053034)),
 (194, np.float64(0.0)),
 (195, np.float64(0.001863002705476742)),
 (196, np.float64(0.008600963866945768)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.01802722395409921)),
 (201, np.float64(0.01670653488368448)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.004550626310168712)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.005101013106047651)),
 (208, np.float64(0.005416874434647647)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (212, np.float64(0.0)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.01522274685487474)),
 (216, np.float64(0.0)),
 (217, np.float64(0.039872241064626404)),
 (218, np.float64(0.004112034777997874)),
 (219, np.float64(0.014218731112563738)),
 (220, np.float64(0.0)),
 (221, np.float64(0.01135938965707746)),
 (222, np.float64(0.005943291517007921)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0082221852206939)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.0025373443221215946)),
 (230, np.float64(0.012465490733359917)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.01630588279538204)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.03176572025069503)),
 (240, np.float64(0.010367656083002372)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.006072289307671936)),
 (244, np.float64(0.012828301574596)),
 (245, np.float64(0.0)),
 (246, np.float64(0.005058634203393212)),
 (247, np.float64(0.0)),
 (248, np.float64(0.0)),
 (249, np.float64(0.0)),
 (250, np.float64(0.018422746732442638)),
 (251, np.float64(0.005447490063568988)),
 (252, np.float64(0.006061728136720759)),
 (253, np.float64(0.0)),
 (254, np.float64(0.0)),
 (255, np.float64(0.0)),
 (256, np.float64(0.0)),
 (257, np.float64(0.0)),
 (258, np.float64(0.013274012995772055)),
 (259, np.float64(0.0)),
 (260, np.float64(0.009467001824676791)),
 (261, np.float64(0.0)),
 (262, np.float64(0.0035115345545975135)),
 (263, np.float64(0.0051034724054053165)),
 (264, np.float64(0.0)),
 (265, np.float64(0.006063387360010476)),
 (266, np.float64(0.0)),
 (267, np.float64(0.0)),
 (268, np.float64(0.006976794687272658)),
 (269, np.float64(0.0)),
 (270, np.float64(0.006637304005723933)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.005900232625038147)),
 (278, np.float64(0.0026723140601167187)),
 (279, np.float64(0.012740212081894582)),
 (280, np.float64(0.0)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.005912225557948146)),
 (288, np.float64(0.0035714751506568452)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0032421453355610643)),
 (291, np.float64(0.0)),
 (292, np.float64(0.05727954688516983)),
 (293, np.float64(0.016596284724880346)),
 (294, np.float64(0.0)),
 (295, np.float64(0.0)),
 (296, np.float64(0.0)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.023210422359585904)),
 (300, np.float64(0.0)),
 (301, np.float64(0.010652723183442701)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.007435264997291652)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.006748678719965006)),
 (311, np.float64(0.006948541850236991)),
 (312, np.float64(0.0)),
 (313, np.float64(0.0)),
 (314, np.float64(0.005980466732601246)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.01964459284103381)),
 (319, np.float64(0.008024534467967075)),
 (320, np.float64(0.015517816736162492)),
 (321, np.float64(0.010195583596528814)),
 (322, np.float64(0.003178343558168737)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.010108705430220268)),
 (328, np.float64(0.05311145310957436)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.014914825243391789)),
 (332, np.float64(0.006798114170382386)),
 (333, np.float64(0.0)),
 (334, np.float64(0.0)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0069386837726103925)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.015191878885034281)),
 (345, np.float64(0.0206760412085687)),
 (346, np.float64(0.024449983927282225)),
 (347, np.float64(0.009589945284158236)),
 (348, np.float64(0.0)),
 (349, np.float64(0.012795179436589251)),
 (350, np.float64(0.0)),
 (351, np.float64(0.00330968496851363)),
 (352, np.float64(0.0)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.0)),
 (357, np.float64(0.008267898381873891)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0)),
 (363, np.float64(0.0)),
 (364, np.float64(0.0)),
 (365, np.float64(0.010998064093816297)),
 (366, np.float64(0.0)),
 (367, np.float64(0.007210194441079518)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.03259798795482715)),
 (372, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.03526354259620173)),
 (377, np.float64(0.01937286729691708)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.01910317889489363)),
 (381, np.float64(0.030187708217876807)),
 (382, np.float64(0.04790774256075744)),
 (383, np.float64(0.043867079026466235)),
 (384, np.float64(0.048461178189764746)),
 (385, np.float64(0.03455851684253136)),
 (386, np.float64(0.08771937706588034)),
 (387, np.float64(0.08068547552307254)),
 (388, np.float64(0.009542561409583122)),
 (389, np.float64(0.00824982153318222)),
 (390, np.float64(0.004257996914081042)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.018316016554710247)),
 (395, np.float64(0.014397264799521723)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.009278779729985816)),
 (399, np.float64(0.0)),
 (400, np.float64(0.002143633688496597)),
 (401, np.float64(0.0)),
 (402, np.float64(0.003541576929069753)),
 (403, np.float64(0.006246351827402825)),
 (404, np.float64(0.0)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.0)),
 (409, np.float64(0.004788725485694456)),
 (410, np.float64(0.00878223760051153)),
 (411, np.float64(0.009387421403079865)),
 (412, np.float64(0.0076221129980028795)),
 (413, np.float64(0.018000398597317405)),
 (414, np.float64(0.025829434366243718)),
 (415, np.float64(0.0074377157539966526)),
 (416, np.float64(0.01765842902178651)),
 (417, np.float64(0.0)),
 (418, np.float64(0.014883233263546078)),
 (419, np.float64(0.00620565068896807)),
 (420, np.float64(0.006218996134472146)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.004298991987737779)),
 (426, np.float64(0.0)),
 (427, np.float64(0.007785994708731734)),
 (428, np.float64(0.013850543776355556)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.010517159069115763)),
 (434, np.float64(0.017792614031358227)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.009876289834308005)),
 (440, np.float64(0.0)),
 (441, np.float64(0.013899314496173976)),
 (442, np.float64(0.005038851922345142)),
 (443, np.float64(0.01453777231721731)),
 (444, np.float64(0.0)),
 (445, np.float64(0.023048228232332275)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.003293045974681017)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.0033666152246191036)),
 (455, np.float64(0.0)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0052466350187104415)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.009366493939081786)),
 (470, np.float64(0.011792897858782686)),
 (471, np.float64(0.0)),
 (472, np.float64(0.005029595930868163)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.037644228710129825)),
 (476, np.float64(0.025227815384091645)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.020246183164721085)),
 (480, np.float64(0.019556776923365785)),
 (481, np.float64(0.04187268415529162)),
 (482, np.float64(0.0015438558149316484)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.008923067865238209)),
 (489, np.float64(0.01180761679274233)),
 (490, np.float64(0.0)),
 (491, np.float64(0.0)),
 (492, np.float64(0.004134805827897953)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.004480443384514841)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0)),
 (499, np.float64(0.00900732935543386)),
 (500, np.float64(0.0)),
 (501, np.float64(0.003648998668308832)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.009872076176134352)),
 (505, np.float64(0.0)),
 (506, np.float64(0.015715304344789238)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.010147977936916658)),
 (510, np.float64(0.007818610156771103)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.013150291481804627)),
 (515, np.float64(0.0)),
 (516, np.float64(0.0068471265857282)),
 (517, np.float64(0.0201803021695919)),
 (518, np.float64(0.0)),
 (519, np.float64(0.010334242272002806)),
 (520, np.float64(0.0)),
 (521, np.float64(0.009979251756712267)),
 (522, np.float64(0.0)),
 (523, np.float64(0.01210161281332153)),
 (524, np.float64(0.024727304148580195)),
 (525, np.float64(0.02936753322855205)),
 (526, np.float64(0.007098585900162209)),
 (527, np.float64(0.005717524880201846)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.02040687236443465)),
 (533, np.float64(0.012025662746418548)),
 (534, np.float64(0.03272295709517777)),
 (535, np.float64(0.04142003234113253)),
 (536, np.float64(0.030037477651193707)),
 (537, np.float64(0.02331026202872228)),
 (538, np.float64(0.008808942202620462)),
 (539, np.float64(0.0192753822234788)),
 (540, np.float64(0.013016202963907072)),
 (541, np.float64(0.0)),
 (542, np.float64(0.007103501704491174)),
 (543, np.float64(0.012148123109800239)),
 (544, np.float64(0.0)),
 (545, np.float64(0.020087785176954483)),
 (546, np.float64(0.0)),
 (547, np.float64(0.025048888556652753)),
 (548, np.float64(0.0091828661292723)),
 (549, np.float64(0.008169903633949734)),
 (550, np.float64(0.0048691800929089165)),
 (551, np.float64(0.008733249229186894)),
 (552, np.float64(0.0)),
 (553, np.float64(0.023991344874062414)),
 (554, np.float64(0.006010384351080899)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.034697413119942094)),
 (558, np.float64(0.010799751809734786)),
 (559, np.float64(0.0)),
 (560, np.float64(0.004428737865943228)),
 (561, np.float64(0.0)),
 (562, np.float64(0.03340805061998169)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.005142764652632)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.016331834064826526)),
 (569, np.float64(0.007774489353442283)),
 (570, np.float64(0.0)),
 (571, np.float64(0.0)),
 (572, np.float64(0.021002071259172077)),
 (573, np.float64(0.0)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.013379819476204476)),
 (577, np.float64(0.006077086777791235)),
 (578, np.float64(0.017059522992135326)),
 (579, np.float64(0.01122300509703132)),
 (580, np.float64(0.0)),
 (581, np.float64(0.0)),
 (582, np.float64(0.0)),
 (583, np.float64(0.009078696910692397)),
 (584, np.float64(0.00571820970965813)),
 (585, np.float64(0.02383646153156262)),
 (586, np.float64(0.009648078711772904)),
 (587, np.float64(0.011040856469812205)),
 (588, np.float64(0.0)),
 (589, np.float64(0.007527086919235615)),
 (590, np.float64(0.004659015414491124)),
 (591, np.float64(0.00605835425524422)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.016995657647048364)),
 (595, np.float64(0.0)),
 (596, np.float64(0.0038835856848075615)),
 (597, np.float64(0.010365226215233657)),
 (598, np.float64(0.0)),
 (599, np.float64(0.0)),
 (600, np.float64(0.007765131764317479)),
 (601, np.float64(0.0)),
 (602, np.float64(0.041268180905428845)),
 (603, np.float64(0.013099317102805194)),
 (604, np.float64(0.025097703180889514)),
 (605, np.float64(0.0)),
 (606, np.float64(0.006436680038535129)),
 (607, np.float64(0.0)),
 (608, np.float64(0.0)),
 (609, np.float64(0.0)),
 (610, np.float64(0.002888088999563761)),
 (611, np.float64(0.012284878655846373)),
 (612, np.float64(0.0048397265435296734)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.004137156210366609)),
 (616, np.float64(0.022134291077993293)),
 (617, np.float64(0.008162005960723757)),
 (618, np.float64(0.005308591237628957)),
 (619, np.float64(0.0)),
 (620, np.float64(0.0)),

In [82]:
def sort_des(idx_array):
    sorted_array = sorted(idx_array, key=lambda x: x[1], reverse=True)
    return sorted_array[1:11]

sorted_array = sort_des(idx_array=book_idx)
sorted_array

[(15012, np.float64(0.26822860898560036)),
 (13832, np.float64(0.24321452699078033)),
 (40495, np.float64(0.24237787245890857)),
 (23708, np.float64(0.23429471340904848)),
 (17247, np.float64(0.22106917446108396)),
 (16360, np.float64(0.21985578691770066)),
 (6879, np.float64(0.21816938715351064)),
 (5935, np.float64(0.2136734315443305)),
 (7916, np.float64(0.21320044389731063)),
 (39114, np.float64(0.201853633810062))]

# Get the book names from the indices

In [83]:
sorted_array[1:6]

[(13832, np.float64(0.24321452699078033)),
 (40495, np.float64(0.24237787245890857)),
 (23708, np.float64(0.23429471340904848)),
 (17247, np.float64(0.22106917446108396)),
 (16360, np.float64(0.21985578691770066))]

In [84]:
def get_book_name(rec_books):
    rec_books_info = []
    for i in rec_books:
        
        rec_books_info.append(df.iloc[i[0], :])
        
    return pd.DataFrame(rec_books_info)

result = get_book_name(sorted_array)
# result = pd.DataFrame(result)
result

,Id,Name,Authors,Publish year,Rating,Description,Text feature
15012,727604,The Soul Beneath the Skin: The Unseen Hearts a...,David Nimmons,2002,3.88,surprise think provoke book begin obvious fact...,David Nimmons The Soul Beneath the Skin: The U...
13832,725500,Life Outside: The Signorile Report on Gay Men:...,Michelangelo Signorile,1998,3.68,strong popular em em magazine columnist michel...,Michelangelo Signorile Life Outside: The Signo...
40495,774575,Gay Men at the Millennium,Michael Lowenthal,1997,4.40,core issue face gay community close millennium...,Michael Lowenthal Gay Men at the Millennium Co...
23708,743801,Lavender Culture,Karla Jay,1994,3.55,influence gays lesbians language literature th...,Karla Jay Lavender Culture The influence of ga...
17247,731667,Queer Wars: The New Gay Right and Its Critics,Paul A. Robinson,2006,4.05,rebellion stonewall recent battle sex marriage...,Paul A. Robinson Queer Wars: The New Gay Right...
16360,730029,"If You Seduce a Straight Person, Can You Make ...",John P. De Cecco,1993,4.00,debate whether people bear homosexual biologic...,John P. De Cecco If You Seduce a Straight Pers...
6879,712601,Art and Sex in Greenwich Village: A Memoir of ...,Felice Picano,2007,3.82,decade stonewall rebellions small gay press na...,Felice Picano Art and Sex in Greenwich Village...
5935,710934,Gay by the Bay: A History of Queer Culture in ...,Susan Stryker,1996,3.89,fabulous montage word image first book ever ch...,Susan Stryker Gay by the Bay: A History of Que...
7916,714426,Men Like Us : The GMHC Complete Guide to Gay M...,Daniel Wolfe,2000,4.06,offer practical advice gay men exercise diet m...,Daniel Wolfe Men Like Us : The GMHC Complete G...
39114,772020,John Gay and the London Theatre,Calhoun Winton,1993,3.00,beggar opera often refer today first musical c...,Calhoun Winton John Gay and the London Theatre...

# Put everything together

In [89]:
def get_rec_books(book_idx, df):
    selected_book = df.iloc[book_idx:book_idx+1, :]
    data = preprocess_dataframe(df=df, column_name='Text feature')
    matrix = get_text_feature(data)
    book_sim = calculate_cosine_similarity_of_a_target_book(book=matrix[book_idx], tfidf_matrix=matrix)
    book_sim = add_indices(book_sim)
    book_sim = sort_des(book_sim)
    result = get_book_name(rec_books=book_sim)
    
    return selected_book, result

selected_book, rec_books = get_rec_books(df=df, book_idx=1000)

In [90]:
rec_books

,Id,Name,Authors,Publish year,Rating,Description,Text feature
35161,764815,Beginning Ruby: From Novice to Professional,Peter Cooper,2007,3.83,ruby perhaps best know engine power hugely pop...,peter cooper begin ruby novice professional ru...
3610,706694,"This Way, Ruby!",Jonathan Emmett,2007,3.81,ruby brothers sisters always race search adven...,jonathan emmett way ruby ruby brothers sisters...
42804,778985,A Revolution in Eating: How the Quest for Food...,James McWilliams,2005,3.92,,jam mcwilliams revolution eat quest food shape...
3612,706696,The Ruby Way,Hal Fulton,2001,3.90,ruby way assume reader already familiar subjec...,hal fulton ruby way ruby way assume reader alr...
45891,784687,Bunny Party,Rosemary Wells,2003,3.72,grandma birthday max ruby party ruby invite se...,rosemary well bunny party grandma birthday max...
25912,747787,Country Loving,Julie Highmore,2003,3.11,life slow alarmingly moment ruby grant oliver ...,julie highmore country love life slow alarming...
37429,768954,Cow Crimes and the Mustang Menace (Ruby Taylor...,Sharon Dunn,2005,3.90,award win series continue mystery ruby taylor ...,sharon dunn cow crimes mustang menace ruby tay...
35794,765883,Ruby in a Nutshell,Yukihiro Matsumoto,2007,3.39,write yukihiro matsumoto matz creator language...,yukihiro matsumoto ruby nutshell write yukihir...
12496,723071,One Summer Night,Gerri Hill,2004,3.82,college professor johanna marshall swear would...,gerri hill one summer night college professor ...
45894,784690,Ruby's Beauty Shop,Rosemary Wells,2004,3.80,welcome ruby beauty shop guess max say max sis...,rosemary well ruby beauty shop welcome ruby be...

In [91]:
selected_book = pd.DataFrame(selected_book)
selected_book

,Id,Name,Authors,Publish year,Rating,Description,Text feature
1000,701907,"Diary of a Slave Girl, Ruby Jo",K.J. McWilliams,2001,4.26,,k j mcwilliams diary slave girl ruby jo

In [92]:
print(f"Selected book: '{selected_book['Name'].iloc[0]}'")
print(f"Selected book description: '{selected_book['Description'].iloc[0]}'\n")
for name in rec_books['Name']: 
    print(f"{name}")

Selected book: 'Diary of a Slave Girl, Ruby Jo'
Selected book description: ''

Beginning Ruby: From Novice to Professional
This Way, Ruby!
A Revolution in Eating: How the Quest for Food Shaped America
The Ruby Way
Bunny Party
Country Loving
Cow Crimes and the Mustang Menace (Ruby Taylor Mystery #3)
Ruby in a Nutshell
One Summer Night
Ruby's Beauty Shop