# Import libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Get the data

In [4]:
# Load the dataset from the CSV file
dataset = pd.read_csv('../data/book700k-800k.csv')
df = pd.DataFrame({'Id': dataset['Id'],
                        'Name': dataset['Name'],
                        'Authors': dataset['Authors'],
                        'Rating': dataset['Rating'],
                        'Description': dataset['Description']})

# Display the first few rows of the dataset
df.head

<bound method NDFrame.head of            Id                                               Name  \
0      700000  A Passion to Preserve: Gay Men as Keepers of C...
1      700002  Culture Keepers-Florida: Oral History of the A...
2      700003  Holiday Favorites: The Best of the Williams-So...
3      700004  Soups, Salads & Starters: the Best of Williams...
4      700005                              Breakfasts & Brunches
...       ...                                                ...
54268  799991           Piano Concerto Highlights for Solo Piano
54269  799993  Noggin King of the Nogs (The Sagas of Noggin t...
54270  799994  No Greater Glory: The Four Immortal Chaplains ...
54271  799996  The White Company by Arthur Conan Doyle, Ficti...
54272  799997                    Livewire Real Lives Dawn Fraser

                     Authors  Rating  \
0               Will Fellows    3.75
1      Deborah Johnson-Simon    0.00
2            Allen Rosenberg    4.55
3            Allan Rosenberg    4.70
4            Time-Life Books    3.88
...                      ...     ...
54268         Felix Guenther    5.00
54269        Oliver Postgate    4.38
54270            Dan Kurzman    4.02
54271     Arthur Conan Doyle    3.89
54272            Ian Jackson    0.00

                                             Description
0      From large cities to rural communities, gay me...
1                                                    NaN
2      This collector's edition features fabulous ful...
3                                                    NaN
4      America's most respected cookware retailer, th...
...                                                  ...
54268  Concertos are every pianist's pinnacle of perf...
54269  1. King of the Nogs --<br />2. The ice dragon ...
54270  The sinking of the <i>Dorchester</i> in the ic...
54271  "By my hilt!" cried the other, "if you were to...
54272  This book tells the story of Dawn Fraser, vote...

[54273 rows x 5 columns]>

In [96]:
# Replace Nan values with ''
df['Description'] = df['Description'].fillna('')
ori_description = df['Description']

In [10]:
df['Description'][0]

'From large cities to rural communities, gay men have long been impassioned pioneers as keepers of culture: rescuing and restoring decrepit buildings, revitalizing blighted neighborhoods, saving artifacts and documents of historical significance. <i>A Passion to Preserve</i> explores this authentic and complex dimension of gay men’s lives by profiling early and contemporary preservationists from throughout the United States, highlighting contributions to the larger culture that gays are exceptionally inclined to make.'

# Data preprocessing

In [ ]:
import re
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Initialize the stopwords
stop_words = set(stopwords.words('english'))

def preprocessing_text(text):
    # Convert the input text to string
    text = str(text)
    
    # Convert text to lowercase
    text = text.lower()
    
    # Remove special characters and digits and replace them with a spcae
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    
    # Tokenize the text
    tokens = nltk.word_tokenize(text)
    
    # Remove stop words
    tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatize the tokens (convert words into their base dictionary form, ex. cats->cat)
    tokens = [lemmatizer.lemmatize(word, pos='v') for word in tokens]
    
    # Return the processed text as a string
    return " ".join(tokens)


def preprocess_dataframe(df, column_name):
    df[column_name ]= df[column_name].apply(preprocessing_text)
    return df

df = preprocess_dataframe(df=df, column_name='Description')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\thlam\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [21]:
df['Description'].head

<bound method NDFrame.head of 0        large city rural community gay men long impass...
1
2        collector edition feature fabulous full color ...
3
4        america respect cookware retailer world larges...
                               ...
54268    concerto every pianist pinnacle performance ra...
54269    king nog br ice dragon br fly machine br omrud...
54270    sink dorchester icy water greenland shortly mi...
54271    hilt cry cross narrow sea would find thick bee...
54272    book tell story dawn fraser vote greatest fema...
Name: Description, Length: 54273, dtype: str>

# Get text features using tf-idf

In [100]:
from sklearn.feature_extraction.text import TfidfVectorizer

def get_text_feature(df):
    description = df['Description']
    # Text feature
    tfidf = TfidfVectorizer(stop_words="english",
                            strip_accents='ascii',
                            token_pattern=r'\w+')

    tfidf_matrix = tfidf.fit_transform(description)
    tfidf.get_feature_names_out()
    
    return tfidf_matrix
tfidf_matrix = get_text_feature(df=df)

# Calculate cosine similarity
`from sklearn.metrics.pairwise import cosine_similarity`

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

def calculate_cosine_similarity_of_a_target_book(book, tfidf_matrix):
    """Calculate the cosine similarity between a target book and all books
    in the TF-IDF matrix.

    Args:
        book (scipy.sparse.csr_matrix): 
            A single TF-IDF row vector representing the target book.
            Shape should be (1, n_features).
        tfidf_matrix (scipy.sparse.csr_matrix_): 
            TF-IDF matrix containing all book vectors.
            Shape should be (n_books, n_features).

    Returns:
        numpy.ndarray: A 2D array containing cosine similarity scores between the target book and 
        every book in the TF-IDF matrix.
        Shape will be (1, n_books).
    """
    X = book
    Y = tfidf_matrix
    cs = cosine_similarity(X, Y)
    return cs

book = calculate_cosine_similarity_of_a_target_book(tfidf_matrix=tfidf_matrix, book=tfidf_matrix[0])
book

array([[1.        , 0.        , 0.        , ..., 0.03131061, 0.00277451,
        0.00542904]], shape=(1, 54273))

# Add indices to the similarity array

In [44]:
tfidf_matrix.shape[0]

54273

In [62]:
def add_indices(sim_array):
    indexed_array = []
    for i, s in zip(range(tfidf_matrix.shape[0]), sim_array[0]):
        indexed_array.append((i, s))
    return indexed_array
    
book_idx = add_indices(book)
book_idx

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(0.0)),
 (5, np.float64(0.004343602419170702)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.02560800854693365)),
 (9, np.float64(0.005483288853473634)),
 (10, np.float64(0.014774125071541046)),
 (11, np.float64(0.001715126662856703)),
 (12, np.float64(0.037609786801544615)),
 (13, np.float64(0.0)),
 (14, np.float64(0.02898527390424989)),
 (15, np.float64(0.0)),
 (16, np.float64(0.01481165486550844)),
 (17, np.float64(0.0027762287508407255)),
 (18, np.float64(0.003977473154942162)),
 (19, np.float64(0.022580899970841478)),
 (20, np.float64(0.011388665056520492)),
 (21, np.float64(0.006782134025799732)),
 (22, np.float64(0.04438433388409871)),
 (23, np.float64(0.0)),
 (24, np.float64(0.028444166959296278)),
 (25, np.float64(0.02414786837589122)),
 (26, np.float64(0.01228285851199043)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.0)),
 (31, np.float64(0.006880566765019242)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0026423547751409765)),
 (35, np.float64(0.0)),
 (36, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.00763809499246059)),
 (40, np.float64(0.0)),
 (41, np.float64(0.029443325432609833)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.03024063881030604)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.004691744802426476)),
 (50, np.float64(0.0)),
 (51, np.float64(0.0157808186738172)),
 (52, np.float64(0.020424462605711548)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.023324509744403494)),
 (56, np.float64(0.0)),
 (57, np.float64(0.013005016929128798)),
 (58, np.float64(0.004300378378252174)),
 (59, np.float64(0.0)),
 (60, np.float64(0.02007481471913704)),
 (61, np.float64(0.007197299568148777)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.009406982105049266)),
 (65, np.float64(0.014525279531485623)),
 (66, np.float64(0.022652055664676162)),
 (67, np.float64(0.0)),
 (68, np.float64(0.019813340674758612)),
 (69, np.float64(0.0)),
 (70, np.float64(0.009338377029004955)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.016698017505197216)),
 (75, np.float64(0.010867135636979313)),
 (76, np.float64(0.0)),
 (77, np.float64(0.03971642049600932)),
 (78, np.float64(0.013625931644849786)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.010557333434593074)),
 (83, np.float64(0.0)),
 (84, np.float64(0.016352877943375112)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.032316102629780324)),
 (88, np.float64(0.04234143502092734)),
 (89, np.float64(0.024722701390951007)),
 (90, np.float64(0.006804939454990904)),
 (91, np.float64(0.022536838794330966)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0030852400460700644)),
 (94, np.float64(0.03237839233666573)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.002173764973521625)),
 (98, np.float64(0.004214744510691638)),
 (99, np.float64(0.021292806160680883)),
 (100, np.float64(0.0)),
 (101, np.float64(0.024793120558175695)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.019386293005567597)),
 (107, np.float64(0.0)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.019902880107978388)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.008011325514879639)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.009732073323748402)),
 (124, np.float64(0.010681929911584084)),
 (125, np.float64(0.022670308968633045)),
 (126, np.float64(0.012569196726975713)),
 (127, np.float64(0.02491690527357316)),
 (128, np.float64(0.022738243481255086)),
 (129, np.float64(0.021617774247019717)),
 (130, np.float64(0.016916708467558002)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0029214047559352157)),
 (135, np.float64(0.0)),
 (136, np.float64(0.006600888218589577)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.03624163735890164)),
 (140, np.float64(0.0)),
 (141, np.float64(0.017895354020994483)),
 (142, np.float64(0.028931718871199295)),
 (143, np.float64(0.018612840370390897)),
 (144, np.float64(0.0)),
 (145, np.float64(0.012203886866356092)),
 (146, np.float64(0.02823071098896534)),
 (147, np.float64(0.012137293367398879)),
 (148, np.float64(0.003740163652754343)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.004641587617028308)),
 (152, np.float64(0.0)),
 (153, np.float64(0.00851420719389875)),
 (154, np.float64(0.002923265064790087)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.026585241006698096)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.013797209251716756)),
 (162, np.float64(0.0)),
 (163, np.float64(0.014060402312842408)),
 (164, np.float64(0.0)),
 (165, np.float64(0.01244306506919634)),
 (166, np.float64(0.002505561371852224)),
 (167, np.float64(0.025898830969730717)),
 (168, np.float64(0.01797063667365579)),
 (169, np.float64(0.003059231079335236)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0033602848676822484)),
 (173, np.float64(0.004440845229638478)),
 (174, np.float64(0.006360338336038225)),
 (175, np.float64(0.0)),
 (176, np.float64(0.022479243113504042)),
 (177, np.float64(0.0)),
 (178, np.float64(0.01964285020894513)),
 (179, np.float64(0.0)),
 (180, np.float64(0.020925294377529328)),
 (181, np.float64(0.040432469084150845)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.016937072278934175)),
 (186, np.float64(0.024858254499185866)),
 (187, np.float64(0.0)),
 (188, np.float64(0.02517514530723079)),
 (189, np.float64(0.02568220410398571)),
 (190, np.float64(0.027290608490033966)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.007178150735305679)),
 (194, np.float64(0.0)),
 (195, np.float64(0.0036270803778812267)),
 (196, np.float64(0.010691036530489485)),
 (197, np.float64(0.0024212510690207584)),
 (198, np.float64(0.004728773219036671)),
 (199, np.float64(0.0)),
 (200, np.float64(0.027421056837767903)),
 (201, np.float64(0.022537644891734217)),
 (202, np.float64(0.009062073874838998)),
 (203, np.float64(0.0)),
 (204, np.float64(0.004604039637279733)),
 (205, np.float64(0.0)),
 (206, np.float64(0.005474198269600545)),
 (207, np.float64(0.007769814522118556)),
 (208, np.float64(0.014883177340097468)),
 (209, np.float64(0.0)),
 (210, np.float64(0.007421831057890679)),
 (211, np.float64(0.0)),
 (212, np.float64(0.007047830570288605)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.01696757599107044)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.004629898238162873)),
 (219, np.float64(0.019778888188670248)),
 (220, np.float64(0.0)),
 (221, np.float64(0.01301364069955142)),
 (222, np.float64(0.00781592240992606)),
 (223, np.float64(0.002635137247908637)),
 (224, np.float64(0.015103779784231736)),
 (225, np.float64(0.0)),
 (226, np.float64(0.01245517046584138)),
 (227, np.float64(0.0)),
 (228, np.float64(0.013765568165977403)),
 (229, np.float64(0.017626850014326068)),
 (230, np.float64(0.0397161023107464)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.01890755499255124)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.03024063881030604)),
 (239, np.float64(0.0)),
 (240, np.float64(0.015310727518956702)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.009989101444554432)),
 (244, np.float64(0.020853015390967688)),
 (245, np.float64(0.0)),
 (246, np.float64(0.008036357227541894)),
 (247, np.float64(0.010542905593440776)),
 (248, np.float64(0.0018205933631393909)),
 (249, np.float64(0.01892109542965008)),
 (250, np.float64(0.025340140447239035)),
 (251, np.float64(0.015408166481043588)),
 (252, np.float64(0.008333675330688363)),
 (253, np.float64(0.03024063881030604)),
 (254, np.float64(0.0056548459914382765)),
 (255, np.float64(0.004945887319365938)),
 (256, np.float64(0.002085678027866929)),
 (257, np.float64(0.0032114203104778084)),
 (258, np.float64(0.014692020827938416)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0140643226079207)),
 (261, np.float64(0.0)),
 (262, np.float64(0.003184511356077089)),
 (263, np.float64(0.013613314553401487)),
 (264, np.float64(0.0)),
 (265, np.float64(0.014256791548943847)),
 (266, np.float64(0.007344857202318701)),
 (267, np.float64(0.0)),
 (268, np.float64(0.016678223412104905)),
 (269, np.float64(0.0)),
 (270, np.float64(0.016743590293069828)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.01744469127732394)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.0022904936391601274)),
 (278, np.float64(0.007219014207381575)),
 (279, np.float64(0.027819653408092067)),
 (280, np.float64(0.004520263074988113)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.007941340635429351)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0030819047188091107)),
 (289, np.float64(0.007502931777267968)),
 (290, np.float64(0.005004044384286273)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.005895756197592688)),
 (296, np.float64(0.09601765142041259)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.024509177908144397)),
 (300, np.float64(0.0)),
 (301, np.float64(0.021566634280293016)),
 (302, np.float64(0.007392885537861604)),
 (303, np.float64(0.0)),
 (304, np.float64(0.011551325558195429)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.002460866236571299)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.010962835088752091)),
 (311, np.float64(0.01604730216287775)),
 (312, np.float64(0.004427318852326078)),
 (313, np.float64(0.0)),
 (314, np.float64(0.014079783309134779)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0097748470241269)),
 (318, np.float64(0.01693407557606502)),
 (319, np.float64(0.012862748861293252)),
 (320, np.float64(0.021992108626615)),
 (321, np.float64(0.015962765984553855)),
 (322, np.float64(0.009714024199525537)),
 (323, np.float64(0.008877980516382491)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.022550771543910053)),
 (328, np.float64(0.06916264807614389)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.02694619275610942)),
 (332, np.float64(0.0085858899415275)),
 (333, np.float64(0.011756059506574938)),
 (334, np.float64(0.005963150009820865)),
 (335, np.float64(0.005280815692900236)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.022099903842508695)),
 (340, np.float64(0.0)),
 (341, np.float64(0.006558221899474109)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.02262177481682806)),
 (345, np.float64(0.01960978566130121)),
 (346, np.float64(0.02390795196845607)),
 (347, np.float64(0.011113539260840861)),
 (348, np.float64(0.0)),
 (349, np.float64(0.015240114493411535)),
 (350, np.float64(0.0)),
 (351, np.float64(0.00913539785104036)),
 (352, np.float64(0.002293207541463743)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.0)),
 (357, np.float64(0.010117881435507502)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0021903590233441263)),
 (363, np.float64(0.0)),
 (364, np.float64(0.006550058569839844)),
 (365, np.float64(0.007950001165771173)),
 (366, np.float64(0.0079037207392786)),
 (367, np.float64(0.0276333209237734)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.034766439339491646)),
 (372, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.04257636151218611)),
 (377, np.float64(0.019592156879768022)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.021893438435347252)),
 (381, np.float64(0.026160250455054858)),
 (382, np.float64(0.02472533239031503)),
 (383, np.float64(0.05380401069532919)),
 (384, np.float64(0.04980320775271832)),
 (385, np.float64(0.020432932774712233)),
 (386, np.float64(0.0833991549893884)),
 (387, np.float64(0.07822081040570766)),
 (388, np.float64(0.014443848840803696)),
 (389, np.float64(0.011675129484238149)),
 (390, np.float64(0.004216028399856521)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.023089300935448524)),
 (395, np.float64(0.01647465548055835)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.023477730069585315)),
 (399, np.float64(0.0)),
 (400, np.float64(0.004499678382680038)),
 (401, np.float64(0.011852310982506522)),
 (402, np.float64(0.005140533535666394)),
 (403, np.float64(0.006682364199611839)),
 (404, np.float64(0.0)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.03024063881030604)),
 (409, np.float64(0.021395556966057043)),
 (410, np.float64(0.009324853527761167)),
 (411, np.float64(0.014084483490813919)),
 (412, np.float64(0.011028706636621772)),
 (413, np.float64(0.032635364523545714)),
 (414, np.float64(0.02640048567814298)),
 (415, np.float64(0.045932232564953)),
 (416, np.float64(0.034896359942922055)),
 (417, np.float64(0.0)),
 (418, np.float64(0.020618073265251655)),
 (419, np.float64(0.018684247011185096)),
 (420, np.float64(0.01167788281884616)),
 (421, np.float64(0.004108112345265723)),
 (422, np.float64(0.0)),
 (423, np.float64(0.003325350581884806)),
 (424, np.float64(0.0)),
 (425, np.float64(0.008876086035980547)),
 (426, np.float64(0.0)),
 (427, np.float64(0.009046987167807255)),
 (428, np.float64(0.03224843043583145)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.01235502515285113)),
 (432, np.float64(0.0)),
 (433, np.float64(0.015101819310020316)),
 (434, np.float64(0.016640487282042912)),
 (435, np.float64(0.004397118856381855)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0030632814366410416)),
 (438, np.float64(0.0)),
 (439, np.float64(0.013316233132316333)),
 (440, np.float64(0.0)),
 (441, np.float64(0.024309871810217216)),
 (442, np.float64(0.006246469795241982)),
 (443, np.float64(0.02819469059642574)),
 (444, np.float64(0.0)),
 (445, np.float64(0.07734028122063004)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.005670457436278378)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.013368029875882322)),
 (455, np.float64(0.0075472980084968)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0015057896486847197)),
 (459, np.float64(0.006487848527112283)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0022089291589036655)),
 (469, np.float64(0.028534922935606093)),
 (470, np.float64(0.026032287921983706)),
 (471, np.float64(0.01382991858273682)),
 (472, np.float64(0.02682960827942027)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0531332261902007)),
 (476, np.float64(0.0249062824425174)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.01813855751870248)),
 (480, np.float64(0.009626338168698007)),
 (481, np.float64(0.05840655169706968)),
 (482, np.float64(0.0014148893434157747)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.02098921852757334)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.023737959254583472)),
 (489, np.float64(0.02191524122204104)),
 (490, np.float64(0.0)),
 (491, np.float64(0.007586243637220308)),
 (492, np.float64(0.005269010022849745)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.013951364025785127)),
 (496, np.float64(0.021061286777451813)),
 (497, np.float64(0.0029692642988134706)),
 (498, np.float64(0.0)),
 (499, np.float64(0.011500971286814904)),
 (500, np.float64(0.0)),
 (501, np.float64(0.005135992716435048)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.005068880096463791)),
 (505, np.float64(0.0)),
 (506, np.float64(0.023257545272867622)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.01345246391074309)),
 (510, np.float64(0.018669653186926358)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.005789275125334446)),
 (514, np.float64(0.012021704606938063)),
 (515, np.float64(0.0)),
 (516, np.float64(0.00921835898112502)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.009344030649738513)),
 (520, np.float64(0.0)),
 (521, np.float64(0.014030716824574529)),
 (522, np.float64(0.0)),
 (523, np.float64(0.020940531356129683)),
 (524, np.float64(0.02414154610671711)),
 (525, np.float64(0.032302261042889434)),
 (526, np.float64(0.008439688672589825)),
 (527, np.float64(0.018342083589763226)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.021113794900156805)),
 (533, np.float64(0.016800340087840062)),
 (534, np.float64(0.03912815373998125)),
 (535, np.float64(0.04936070977492741)),
 (536, np.float64(0.02781554108157657)),
 (537, np.float64(0.023822842505023145)),
 (538, np.float64(0.01085613663414542)),
 (539, np.float64(0.03350793354890825)),
 (540, np.float64(0.023144309361410476)),
 (541, np.float64(0.0)),
 (542, np.float64(0.011460511576257396)),
 (543, np.float64(0.03730325016715457)),
 (544, np.float64(0.0)),
 (545, np.float64(0.03353475845306465)),
 (546, np.float64(0.0)),
 (547, np.float64(0.035054289252336925)),
 (548, np.float64(0.0371397834606074)),
 (549, np.float64(0.025287796943078436)),
 (550, np.float64(0.007828229610435524)),
 (551, np.float64(0.013876336483161942)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.007061357168764538)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.04073550931413422)),
 (558, np.float64(0.015359963748303621)),
 (559, np.float64(0.0)),
 (560, np.float64(0.016785016400530425)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0433230245698956)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.011543896506379773)),
 (566, np.float64(0.012291963432156336)),
 (567, np.float64(0.0)),
 (568, np.float64(0.028740702278129603)),
 (569, np.float64(0.017476989166967487)),
 (570, np.float64(0.0)),
 (571, np.float64(0.02014046540936617)),
 (572, np.float64(0.01490748801965723)),
 (573, np.float64(0.0022977566096355857)),
 (574, np.float64(0.0)),
 (575, np.float64(0.003941498997173973)),
 (576, np.float64(0.05465829505524442)),
 (577, np.float64(0.01624449204305298)),
 (578, np.float64(0.02511725731107799)),
 (579, np.float64(0.016484848438053746)),
 (580, np.float64(0.0)),
 (581, np.float64(0.012969167686038494)),
 (582, np.float64(0.0)),
 (583, np.float64(0.030675453874674505)),
 (584, np.float64(0.013515838053891935)),
 (585, np.float64(0.04227284809576728)),
 (586, np.float64(0.007385255309392297)),

# Sort descendent

In [63]:
book_idx

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.0)),
 (4, np.float64(0.0)),
 (5, np.float64(0.004343602419170702)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0)),
 (8, np.float64(0.02560800854693365)),
 (9, np.float64(0.005483288853473634)),
 (10, np.float64(0.014774125071541046)),
 (11, np.float64(0.001715126662856703)),
 (12, np.float64(0.037609786801544615)),
 (13, np.float64(0.0)),
 (14, np.float64(0.02898527390424989)),
 (15, np.float64(0.0)),
 (16, np.float64(0.01481165486550844)),
 (17, np.float64(0.0027762287508407255)),
 (18, np.float64(0.003977473154942162)),
 (19, np.float64(0.022580899970841478)),
 (20, np.float64(0.011388665056520492)),
 (21, np.float64(0.006782134025799732)),
 (22, np.float64(0.04438433388409871)),
 (23, np.float64(0.0)),
 (24, np.float64(0.028444166959296278)),
 (25, np.float64(0.02414786837589122)),
 (26, np.float64(0.01228285851199043)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.0)),
 (31, np.float64(0.006880566765019242)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0026423547751409765)),
 (35, np.float64(0.0)),
 (36, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.00763809499246059)),
 (40, np.float64(0.0)),
 (41, np.float64(0.029443325432609833)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.03024063881030604)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.0)),
 (48, np.float64(0.0)),
 (49, np.float64(0.004691744802426476)),
 (50, np.float64(0.0)),
 (51, np.float64(0.0157808186738172)),
 (52, np.float64(0.020424462605711548)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.023324509744403494)),
 (56, np.float64(0.0)),
 (57, np.float64(0.013005016929128798)),
 (58, np.float64(0.004300378378252174)),
 (59, np.float64(0.0)),
 (60, np.float64(0.02007481471913704)),
 (61, np.float64(0.007197299568148777)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.009406982105049266)),
 (65, np.float64(0.014525279531485623)),
 (66, np.float64(0.022652055664676162)),
 (67, np.float64(0.0)),
 (68, np.float64(0.019813340674758612)),
 (69, np.float64(0.0)),
 (70, np.float64(0.009338377029004955)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.016698017505197216)),
 (75, np.float64(0.010867135636979313)),
 (76, np.float64(0.0)),
 (77, np.float64(0.03971642049600932)),
 (78, np.float64(0.013625931644849786)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.010557333434593074)),
 (83, np.float64(0.0)),
 (84, np.float64(0.016352877943375112)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.032316102629780324)),
 (88, np.float64(0.04234143502092734)),
 (89, np.float64(0.024722701390951007)),
 (90, np.float64(0.006804939454990904)),
 (91, np.float64(0.022536838794330966)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0030852400460700644)),
 (94, np.float64(0.03237839233666573)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.002173764973521625)),
 (98, np.float64(0.004214744510691638)),
 (99, np.float64(0.021292806160680883)),
 (100, np.float64(0.0)),
 (101, np.float64(0.024793120558175695)),
 (102, np.float64(0.0)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.019386293005567597)),
 (107, np.float64(0.0)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.019902880107978388)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.008011325514879639)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.009732073323748402)),
 (124, np.float64(0.010681929911584084)),
 (125, np.float64(0.022670308968633045)),
 (126, np.float64(0.012569196726975713)),
 (127, np.float64(0.02491690527357316)),
 (128, np.float64(0.022738243481255086)),
 (129, np.float64(0.021617774247019717)),
 (130, np.float64(0.016916708467558002)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0029214047559352157)),
 (135, np.float64(0.0)),
 (136, np.float64(0.006600888218589577)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.03624163735890164)),
 (140, np.float64(0.0)),
 (141, np.float64(0.017895354020994483)),
 (142, np.float64(0.028931718871199295)),
 (143, np.float64(0.018612840370390897)),
 (144, np.float64(0.0)),
 (145, np.float64(0.012203886866356092)),
 (146, np.float64(0.02823071098896534)),
 (147, np.float64(0.012137293367398879)),
 (148, np.float64(0.003740163652754343)),
 (149, np.float64(0.0)),
 (150, np.float64(0.0)),
 (151, np.float64(0.004641587617028308)),
 (152, np.float64(0.0)),
 (153, np.float64(0.00851420719389875)),
 (154, np.float64(0.002923265064790087)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.026585241006698096)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.013797209251716756)),
 (162, np.float64(0.0)),
 (163, np.float64(0.014060402312842408)),
 (164, np.float64(0.0)),
 (165, np.float64(0.01244306506919634)),
 (166, np.float64(0.002505561371852224)),
 (167, np.float64(0.025898830969730717)),
 (168, np.float64(0.01797063667365579)),
 (169, np.float64(0.003059231079335236)),
 (170, np.float64(0.0)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0033602848676822484)),
 (173, np.float64(0.004440845229638478)),
 (174, np.float64(0.006360338336038225)),
 (175, np.float64(0.0)),
 (176, np.float64(0.022479243113504042)),
 (177, np.float64(0.0)),
 (178, np.float64(0.01964285020894513)),
 (179, np.float64(0.0)),
 (180, np.float64(0.020925294377529328)),
 (181, np.float64(0.040432469084150845)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.0)),
 (185, np.float64(0.016937072278934175)),
 (186, np.float64(0.024858254499185866)),
 (187, np.float64(0.0)),
 (188, np.float64(0.02517514530723079)),
 (189, np.float64(0.02568220410398571)),
 (190, np.float64(0.027290608490033966)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.007178150735305679)),
 (194, np.float64(0.0)),
 (195, np.float64(0.0036270803778812267)),
 (196, np.float64(0.010691036530489485)),
 (197, np.float64(0.0024212510690207584)),
 (198, np.float64(0.004728773219036671)),
 (199, np.float64(0.0)),
 (200, np.float64(0.027421056837767903)),
 (201, np.float64(0.022537644891734217)),
 (202, np.float64(0.009062073874838998)),
 (203, np.float64(0.0)),
 (204, np.float64(0.004604039637279733)),
 (205, np.float64(0.0)),
 (206, np.float64(0.005474198269600545)),
 (207, np.float64(0.007769814522118556)),
 (208, np.float64(0.014883177340097468)),
 (209, np.float64(0.0)),
 (210, np.float64(0.007421831057890679)),
 (211, np.float64(0.0)),
 (212, np.float64(0.007047830570288605)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.01696757599107044)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.004629898238162873)),
 (219, np.float64(0.019778888188670248)),
 (220, np.float64(0.0)),
 (221, np.float64(0.01301364069955142)),
 (222, np.float64(0.00781592240992606)),
 (223, np.float64(0.002635137247908637)),
 (224, np.float64(0.015103779784231736)),
 (225, np.float64(0.0)),
 (226, np.float64(0.01245517046584138)),
 (227, np.float64(0.0)),
 (228, np.float64(0.013765568165977403)),
 (229, np.float64(0.017626850014326068)),
 (230, np.float64(0.0397161023107464)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.01890755499255124)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.0)),
 (237, np.float64(0.0)),
 (238, np.float64(0.03024063881030604)),
 (239, np.float64(0.0)),
 (240, np.float64(0.015310727518956702)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.009989101444554432)),
 (244, np.float64(0.020853015390967688)),
 (245, np.float64(0.0)),
 (246, np.float64(0.008036357227541894)),
 (247, np.float64(0.010542905593440776)),
 (248, np.float64(0.0018205933631393909)),
 (249, np.float64(0.01892109542965008)),
 (250, np.float64(0.025340140447239035)),
 (251, np.float64(0.015408166481043588)),
 (252, np.float64(0.008333675330688363)),
 (253, np.float64(0.03024063881030604)),
 (254, np.float64(0.0056548459914382765)),
 (255, np.float64(0.004945887319365938)),
 (256, np.float64(0.002085678027866929)),
 (257, np.float64(0.0032114203104778084)),
 (258, np.float64(0.014692020827938416)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0140643226079207)),
 (261, np.float64(0.0)),
 (262, np.float64(0.003184511356077089)),
 (263, np.float64(0.013613314553401487)),
 (264, np.float64(0.0)),
 (265, np.float64(0.014256791548943847)),
 (266, np.float64(0.007344857202318701)),
 (267, np.float64(0.0)),
 (268, np.float64(0.016678223412104905)),
 (269, np.float64(0.0)),
 (270, np.float64(0.016743590293069828)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.01744469127732394)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.0)),
 (277, np.float64(0.0022904936391601274)),
 (278, np.float64(0.007219014207381575)),
 (279, np.float64(0.027819653408092067)),
 (280, np.float64(0.004520263074988113)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.007941340635429351)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0030819047188091107)),
 (289, np.float64(0.007502931777267968)),
 (290, np.float64(0.005004044384286273)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.005895756197592688)),
 (296, np.float64(0.09601765142041259)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.024509177908144397)),
 (300, np.float64(0.0)),
 (301, np.float64(0.021566634280293016)),
 (302, np.float64(0.007392885537861604)),
 (303, np.float64(0.0)),
 (304, np.float64(0.011551325558195429)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.002460866236571299)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.010962835088752091)),
 (311, np.float64(0.01604730216287775)),
 (312, np.float64(0.004427318852326078)),
 (313, np.float64(0.0)),
 (314, np.float64(0.014079783309134779)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0097748470241269)),
 (318, np.float64(0.01693407557606502)),
 (319, np.float64(0.012862748861293252)),
 (320, np.float64(0.021992108626615)),
 (321, np.float64(0.015962765984553855)),
 (322, np.float64(0.009714024199525537)),
 (323, np.float64(0.008877980516382491)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.022550771543910053)),
 (328, np.float64(0.06916264807614389)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.02694619275610942)),
 (332, np.float64(0.0085858899415275)),
 (333, np.float64(0.011756059506574938)),
 (334, np.float64(0.005963150009820865)),
 (335, np.float64(0.005280815692900236)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.022099903842508695)),
 (340, np.float64(0.0)),
 (341, np.float64(0.006558221899474109)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.02262177481682806)),
 (345, np.float64(0.01960978566130121)),
 (346, np.float64(0.02390795196845607)),
 (347, np.float64(0.011113539260840861)),
 (348, np.float64(0.0)),
 (349, np.float64(0.015240114493411535)),
 (350, np.float64(0.0)),
 (351, np.float64(0.00913539785104036)),
 (352, np.float64(0.002293207541463743)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.0)),
 (357, np.float64(0.010117881435507502)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0021903590233441263)),
 (363, np.float64(0.0)),
 (364, np.float64(0.006550058569839844)),
 (365, np.float64(0.007950001165771173)),
 (366, np.float64(0.0079037207392786)),
 (367, np.float64(0.0276333209237734)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.034766439339491646)),
 (372, np.float64(0.0)),
 (373, np.float64(0.0)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.04257636151218611)),
 (377, np.float64(0.019592156879768022)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.021893438435347252)),
 (381, np.float64(0.026160250455054858)),
 (382, np.float64(0.02472533239031503)),
 (383, np.float64(0.05380401069532919)),
 (384, np.float64(0.04980320775271832)),
 (385, np.float64(0.020432932774712233)),
 (386, np.float64(0.0833991549893884)),
 (387, np.float64(0.07822081040570766)),
 (388, np.float64(0.014443848840803696)),
 (389, np.float64(0.011675129484238149)),
 (390, np.float64(0.004216028399856521)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.023089300935448524)),
 (395, np.float64(0.01647465548055835)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.023477730069585315)),
 (399, np.float64(0.0)),
 (400, np.float64(0.004499678382680038)),
 (401, np.float64(0.011852310982506522)),
 (402, np.float64(0.005140533535666394)),
 (403, np.float64(0.006682364199611839)),
 (404, np.float64(0.0)),
 (405, np.float64(0.0)),
 (406, np.float64(0.0)),
 (407, np.float64(0.0)),
 (408, np.float64(0.03024063881030604)),
 (409, np.float64(0.021395556966057043)),
 (410, np.float64(0.009324853527761167)),
 (411, np.float64(0.014084483490813919)),
 (412, np.float64(0.011028706636621772)),
 (413, np.float64(0.032635364523545714)),
 (414, np.float64(0.02640048567814298)),
 (415, np.float64(0.045932232564953)),
 (416, np.float64(0.034896359942922055)),
 (417, np.float64(0.0)),
 (418, np.float64(0.020618073265251655)),
 (419, np.float64(0.018684247011185096)),
 (420, np.float64(0.01167788281884616)),
 (421, np.float64(0.004108112345265723)),
 (422, np.float64(0.0)),
 (423, np.float64(0.003325350581884806)),
 (424, np.float64(0.0)),
 (425, np.float64(0.008876086035980547)),
 (426, np.float64(0.0)),
 (427, np.float64(0.009046987167807255)),
 (428, np.float64(0.03224843043583145)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.01235502515285113)),
 (432, np.float64(0.0)),
 (433, np.float64(0.015101819310020316)),
 (434, np.float64(0.016640487282042912)),
 (435, np.float64(0.004397118856381855)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0030632814366410416)),
 (438, np.float64(0.0)),
 (439, np.float64(0.013316233132316333)),
 (440, np.float64(0.0)),
 (441, np.float64(0.024309871810217216)),
 (442, np.float64(0.006246469795241982)),
 (443, np.float64(0.02819469059642574)),
 (444, np.float64(0.0)),
 (445, np.float64(0.07734028122063004)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.005670457436278378)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.013368029875882322)),
 (455, np.float64(0.0075472980084968)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0015057896486847197)),
 (459, np.float64(0.006487848527112283)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0022089291589036655)),
 (469, np.float64(0.028534922935606093)),
 (470, np.float64(0.026032287921983706)),
 (471, np.float64(0.01382991858273682)),
 (472, np.float64(0.02682960827942027)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0531332261902007)),
 (476, np.float64(0.0249062824425174)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.01813855751870248)),
 (480, np.float64(0.009626338168698007)),
 (481, np.float64(0.05840655169706968)),
 (482, np.float64(0.0014148893434157747)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.02098921852757334)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.023737959254583472)),
 (489, np.float64(0.02191524122204104)),
 (490, np.float64(0.0)),
 (491, np.float64(0.007586243637220308)),
 (492, np.float64(0.005269010022849745)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.013951364025785127)),
 (496, np.float64(0.021061286777451813)),
 (497, np.float64(0.0029692642988134706)),
 (498, np.float64(0.0)),
 (499, np.float64(0.011500971286814904)),
 (500, np.float64(0.0)),
 (501, np.float64(0.005135992716435048)),
 (502, np.float64(0.0)),
 (503, np.float64(0.0)),
 (504, np.float64(0.005068880096463791)),
 (505, np.float64(0.0)),
 (506, np.float64(0.023257545272867622)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.01345246391074309)),
 (510, np.float64(0.018669653186926358)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.005789275125334446)),
 (514, np.float64(0.012021704606938063)),
 (515, np.float64(0.0)),
 (516, np.float64(0.00921835898112502)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.009344030649738513)),
 (520, np.float64(0.0)),
 (521, np.float64(0.014030716824574529)),
 (522, np.float64(0.0)),
 (523, np.float64(0.020940531356129683)),
 (524, np.float64(0.02414154610671711)),
 (525, np.float64(0.032302261042889434)),
 (526, np.float64(0.008439688672589825)),
 (527, np.float64(0.018342083589763226)),
 (528, np.float64(0.0)),
 (529, np.float64(0.0)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.021113794900156805)),
 (533, np.float64(0.016800340087840062)),
 (534, np.float64(0.03912815373998125)),
 (535, np.float64(0.04936070977492741)),
 (536, np.float64(0.02781554108157657)),
 (537, np.float64(0.023822842505023145)),
 (538, np.float64(0.01085613663414542)),
 (539, np.float64(0.03350793354890825)),
 (540, np.float64(0.023144309361410476)),
 (541, np.float64(0.0)),
 (542, np.float64(0.011460511576257396)),
 (543, np.float64(0.03730325016715457)),
 (544, np.float64(0.0)),
 (545, np.float64(0.03353475845306465)),
 (546, np.float64(0.0)),
 (547, np.float64(0.035054289252336925)),
 (548, np.float64(0.0371397834606074)),
 (549, np.float64(0.025287796943078436)),
 (550, np.float64(0.007828229610435524)),
 (551, np.float64(0.013876336483161942)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.007061357168764538)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.04073550931413422)),
 (558, np.float64(0.015359963748303621)),
 (559, np.float64(0.0)),
 (560, np.float64(0.016785016400530425)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0433230245698956)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.011543896506379773)),
 (566, np.float64(0.012291963432156336)),
 (567, np.float64(0.0)),
 (568, np.float64(0.028740702278129603)),
 (569, np.float64(0.017476989166967487)),
 (570, np.float64(0.0)),
 (571, np.float64(0.02014046540936617)),
 (572, np.float64(0.01490748801965723)),
 (573, np.float64(0.0022977566096355857)),
 (574, np.float64(0.0)),
 (575, np.float64(0.003941498997173973)),
 (576, np.float64(0.05465829505524442)),
 (577, np.float64(0.01624449204305298)),
 (578, np.float64(0.02511725731107799)),
 (579, np.float64(0.016484848438053746)),
 (580, np.float64(0.0)),
 (581, np.float64(0.012969167686038494)),
 (582, np.float64(0.0)),
 (583, np.float64(0.030675453874674505)),
 (584, np.float64(0.013515838053891935)),
 (585, np.float64(0.04227284809576728)),
 (586, np.float64(0.007385255309392297)),

In [93]:
def sort_des(idx_array):
    sorted_array = sorted(idx_array, key=lambda x: x[1], reverse=True)
    return sorted_array[1:11]

sorted_array = sort_des(idx_array=book_idx)
sorted_array

[(15012, np.float64(0.32975739542736043)),
 (13832, np.float64(0.32438855339360567)),
 (40495, np.float64(0.2944226623400963)),
 (23708, np.float64(0.2814570434343624)),
 (17247, np.float64(0.27820217005352105)),
 (6879, np.float64(0.27788004343571726)),
 (5935, np.float64(0.2766622924502505)),
 (16360, np.float64(0.2682139564220764)),
 (30718, np.float64(0.2630998656455231)),
 (39114, np.float64(0.2594407783148964))]

# Get the book names from the indices

In [ ]:
sorted_array[1:6]

(15012, np.float64(0.32975739542736043))

In [101]:
def get_book_name(rec_books):
    rec_books_info = []
    for i in rec_books:
        
        rec_books_info.append(df.iloc[i[0], :])
        
    return pd.DataFrame(rec_books_info)

result = get_book_name(sorted_array)
# result = pd.DataFrame(result)
result

,Id,Name,Authors,Rating,Description
15012,727604,The Soul Beneath the Skin: The Unseen Hearts a...,David Nimmons,3.88,surprise think provoke book begin obvious fact...
13832,725500,Life Outside: The Signorile Report on Gay Men:...,Michelangelo Signorile,3.68,strong popular em em magazine columnist michel...
40495,774575,Gay Men at the Millennium,Michael Lowenthal,4.40,core issue face gay community close millennium...
23708,743801,Lavender Culture,Karla Jay,3.55,influence gay lesbian language literature thea...
17247,731667,Queer Wars: The New Gay Right and Its Critics,Paul A. Robinson,4.05,rebellion stonewall recent battle sex marriage...
6879,712601,Art and Sex in Greenwich Village: A Memoir of ...,Felice Picano,3.82,decade stonewall rebellion small gay press nam...
5935,710934,Gay by the Bay: A History of Queer Culture in ...,Susan Stryker,3.89,fabulous montage word image first book ever ch...
16360,730029,"If You Seduce a Straight Person, Can You Make ...",John P. De Cecco,4.00,debate whether people bear homosexual biologic...
30718,756813,The Gay Man's Instruction Manual: Advice for a...,Joshua Michaelmas,3.00,finally sound advice gay men today world write...
39114,772020,John Gay and the London Theatre,Calhoun Winton,3.00,beggar opera often refer today first musical c...

# Put everything together

In [110]:
def get_rec_books(book_idx, df):
    data = preprocess_dataframe(df=df, column_name='Description')
    matrix = get_text_feature(data)
    book_sim = calculate_cosine_similarity_of_a_target_book(book=matrix[book_idx], tfidf_matrix=matrix)
    book_sim = add_indices(book_sim)
    book_sim = sort_des(book_sim)
    result = get_book_name(rec_books=book_sim)
    
    return result

rec_books = get_rec_books(df=df, book_idx=2)

In [113]:
rec_books

,Id,Name,Authors,Rating,Description
53714,799047,The Chef's Art: Secrets of Four-Star Cooking a...,Wayne Gisslen,4.44,explain cook work organize step order prepare ...
27608,751055,Pasta Sauces,Time-Life Books,3.75,volume include information home cook need equi...
21345,739339,Vegetarian Cooking: For Beginners,Fiona Watt,4.25,step step illustration tasty delicious recipe ...
21413,739490,Pasta & Pizza for Beginners,Fiona Watt,4.20,step step illustration tasty delicious recipe ...
14333,726362,A French Chef Cooks at Home,Jacques Pépin,4.11,author entitle book jacques pepin french chef ...
31213,757728,Cooking at The Merchant House,Shaun Hill,4.00,cook merchant house show excite home cook reci...
34789,764111,The Complete Guide to Feng Shui,Gill Hale,3.69,practical reference series cover everything he...
27717,751247,Betty Crocker Cookbook: Everything You Need to...,Betty Crocker,4.26,contain mix recipe classic recipe focus health...
34629,763852,The Complete Cooking Light Cookbook,Cooking Light Magazine,4.14,cook interest one stop guide make healthy deli...
7482,713646,Fast Fixes with Mixes: 355 Delicious Recipes f...,Taste of Home,4.02,unique book contain delicious recipe cook acro...

In [115]:
for book in rec_books: 
    print(f"{rec_books.iloc[:, 1]}")

53714    The Chef's Art: Secrets of Four-Star Cooking a...
27608                                         Pasta Sauces
21345                    Vegetarian Cooking: For Beginners
21413                          Pasta & Pizza for Beginners
14333                          A French Chef Cooks at Home
31213                        Cooking at The Merchant House
34789                      The Complete Guide to Feng Shui
27717    Betty Crocker Cookbook: Everything You Need to...
34629                  The Complete Cooking Light Cookbook
7482     Fast Fixes with Mixes: 355 Delicious Recipes f...
Name: Name, dtype: str
53714    The Chef's Art: Secrets of Four-Star Cooking a...
27608                                         Pasta Sauces
21345                    Vegetarian Cooking: For Beginners
21413                          Pasta & Pizza for Beginners
14333                          A French Chef Cooks at Home
31213                        Cooking at The Merchant House
34789                      The Complete Guide to Feng Shui
27717    Betty Crocker Cookbook: Everything You Need to...
34629                  The Complete Cooking Light Cookbook
7482     Fast Fixes with Mixes: 355 Delicious Recipes f...
Name: Name, dtype: str
53714    The Chef's Art: Secrets of Four-Star Cooking a...
27608                                         Pasta Sauces
21345                    Vegetarian Cooking: For Beginners
21413                          Pasta & Pizza for Beginners
14333                          A French Chef Cooks at Home
31213                        Cooking at The Merchant House
34789                      The Complete Guide to Feng Shui
27717    Betty Crocker Cookbook: Everything You Need to...
34629                  The Complete Cooking Light Cookbook
7482     Fast Fixes with Mixes: 355 Delicious Recipes f...
Name: Name, dtype: str
53714    The Chef's Art: Secrets of Four-Star Cooking a...
27608                                         Pasta Sauces
21345                    Vegetarian Cooking: For Beginners
21413                          Pasta & Pizza for Beginners
14333                          A French Chef Cooks at Home
31213                        Cooking at The Merchant House
34789                      The Complete Guide to Feng Shui
27717    Betty Crocker Cookbook: Everything You Need to...
34629                  The Complete Cooking Light Cookbook
7482     Fast Fixes with Mixes: 355 Delicious Recipes f...
Name: Name, dtype: str
53714    The Chef's Art: Secrets of Four-Star Cooking a...
27608                                         Pasta Sauces
21345                    Vegetarian Cooking: For Beginners
21413                          Pasta & Pizza for Beginners
14333                          A French Chef Cooks at Home
31213                        Cooking at The Merchant House
34789                      The Complete Guide to Feng Shui
27717    Betty Crocker Cookbook: Everything You Need to...
34629                  The Complete Cooking Light Cookbook
7482     Fast Fixes with Mixes: 355 Delicious Recipes f...
Name: Name, dtype: str

In [109]:
df.iloc[2, 1]

'Holiday Favorites: The Best of the Williams-Sonoma Kitchen Library'